// This file was automatically generated by 'make' from file 'kernel_spat_to_SH.gen.c'.
// To modify it, please consider modifying kernel_spat_to_SH.gen.c
/*
 * Copyright (c) 2010-2019 Centre National de la Recherche Scientifique.
 * written by Nathanael Schaeffer (CNRS, ISTerre, Grenoble, France).
 * 
 * nathanael.schaeffer@univ-grenoble-alpes.fr
 * 
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software. You can use,
 * modify and/or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 * 
 */

//////////////////////////////////////////////////

	#ifdef HI_LLIM
	#define BASE _an1_hi
	#else
	#define BASE _an1
	#endif

	void GEN3(BASE,NWAY,SUFFIX)(shtns_cfg shtns, double *BrF, cplx *Qlm, const long int llim, const int imlim)
  {
	// TODO: NW should be larger for SHTNS_ISHIOKA ?, or take a different approach.
	#define NW (NWAY*16)
	// another blocking level in theta (64 or 128 should be good)
	#define NBLK (NWAY*16) //24 //(NWAY*3) //24 //96 // (NWAY*3)  //24
	// LSPAN can be 2 or 4
	#define LSPAN 4

	double *alm, *al;
	double *wg, *ct, *st;
	long int nk, k, l,m;
	unsigned m0, mstep;
  #ifndef SHT_AXISYM
	unsigned im;
  #endif
	v2d qq[llim+2];

	// the SSE macro should align these arrays on vector length.
	double rer[NLAT_2 + NW*VSIZE2] SSE;
	double ror[NLAT_2 + NW*VSIZE2] SSE;
  #ifndef SHT_AXISYM
	double rei[NLAT_2 + NW*VSIZE2] SSE;
	double roi[NLAT_2 + NW*VSIZE2] SSE;
  #endif

	nk = NLAT_2;	// copy NLAT_2 to a local variable for faster access (inner loop limit)
	#if _GCC_VEC_
	  nk = ((unsigned) nk+(VSIZE2-1))/VSIZE2;
	#endif
	wg = shtns->wg;		ct = shtns->ct;		st = shtns->st;
	for (k=nk*VSIZE2; k<(nk-1+NW)*VSIZE2; ++k) {		// never written, so this is now done for all m's
		rer[k] = 0.0;		ror[k] = 0.0;
	  #ifndef SHT_AXISYM
		rei[k] = 0.0;		roi[k] = 0.0;
	  #endif
	}

	// ACCESS PATTERN
	const int k_inc = shtns->k_stride_a;
	const int m_inc = shtns->m_stride_a;

	#ifndef _OPENMP
		m0 = 0;		mstep = 1;
	#else
		m0 = omp_get_thread_num();
		mstep = omp_get_num_threads();
		if (m0 == 0)
	#endif
	{		// im=0 : dzl.p = 0.0 and evrything is REAL
		alm = shtns->blm;
		double r0 = 0.0;
		// compute symmetric and antisymmetric parts. (do not weight here, it is cheaper to weight y0)
		SYM_ASYM_M0_Q(BrF, rer, ror, r0)
		Qlm[0] = r0 * alm[0];			// l=0 is done.
		k = 0;
		double* q_ = (double*) qq;
		for (l=0;l<llim;++l) {
			q_[l] = 0.0;
		}
		do {
			al = alm;
			rnd cost[NW], y0[NW], y1[NW];
			rnd rerk[NW], rork[NW];		// help the compiler to cache into registers.
			const int blk_sze = (k+NW <= nk) ? NW : nk-k;		// limit block size to avoid reading garbage as arrays overflow
			for (int j=0; j<blk_sze; ++j) {
				cost[j] = vread(ct, k+j);
				y0[j] = vall(al[0]) * vread(wg, k+j);		// weight of Gauss quadrature appears here
				y1[j] =  (vall(al[1])*y0[j]) * cost[j];
				rerk[j] = vread(rer, k+j);		rork[j] = vread(ror, k+j);		// cache into registers.
			}
			al+=2;	l=1;
			while(l<llim) {
				for (int j=0; j<blk_sze; ++j) {
					y0[j]  = vall(al[1])*(cost[j]*y1[j]) + vall(al[0])*y0[j];
				}
				rnd q = y1[0] * rork[0];
				for (int j=1; j<blk_sze; ++j) {
					q += y1[j] * rork[j];
				}
				q_[l-1]   += reduce_add(q);
				for (int j=0; j<blk_sze; ++j) {
					y1[j]  = vall(al[3])*(cost[j]*y0[j]) + vall(al[2])*y1[j];
				}
				q = y0[0] * rerk[0];
				for (int j=1; j<blk_sze; ++j) {
					q += y0[j] * rerk[j];
				}
				q_[l]     += reduce_add(q);
				al+=4;	l+=2;
			}
			if (l==llim) {
				rnd q = y1[0] * rork[0];
				for (int j=1; j<blk_sze; ++j) {
					q += y1[j] * rork[j];
				}
				q_[l-1]   += reduce_add(q);
			}
			k+=NW;
		} while (k < nk);
		for (l=1; l<=llim; ++l) {
			Qlm[l] = q_[l-1];
		}
		#ifdef SHT_VAR_LTR
			for (l=llim+1; l<= LMAX; ++l) {
				((v2d*)Qlm)[l] = vdup(0.0);
			}
			#ifndef SHT_AXISYM
			if (imlim <= MMAX) {		// zero out m >= imlim
				l = LiM(shtns, imlim*MRES, imlim);
				do {
					((v2d*)Qlm)[l] = vdup(0.0);
				} while(++l < shtns->nlm);
			}
			#endif
		#endif
		m0=mstep;
	}

  #ifndef SHT_AXISYM
	const double mpos_scale = shtns->mpos_scale_analys;		// handles real-norm
	for (im=m0; im<imlim; im+=mstep) {
		m = im*MRES;
		int k0 = shtns->tm[im] / VSIZE2;
		#ifndef SHTNS_ISHIOKA
		alm = shtns->blm + im*(2*(LMAX+1) -m+MRES);
		#else
		alm = shtns->clm + im*(2*(LMAX+1) - m+MRES)/2;
		#endif
		// compute symmetric and anti-symmetric parts:
	#ifndef SHTNS_ISHIOKA
		SYM_ASYM_Q(BrF, rer, ror, rei, roi, k0)
	#else
		SYM_ASYM_Q_ISH(BrF, rer, ror, rei, roi, k0)
	#endif
	
		for (int l=0; l<=llim-m+1; l++) {
			qq[l] = vdup(0.0);
		}
		int k = nk; do {
			k -= NBLK;
			v2d* q = qq;
			rnd y01ct[NBLK][3];		// [0] = y0,  [1] =  y1,  [2] = cos(theta)^2
		#ifdef HI_LLIM
			int ny[NBLK/NWAY];		// exponent to extend double precision range.
			int lnz = llim;			// apriori, we go up to llim.
		#endif
			int imin = (k<k0) ? imin = k0-k-(NWAY-1) : 0;	// the last block may be smaller.
			for (int i=NBLK-NWAY; i>=imin; i-=NWAY) {		// iterate over blocks, start from the right-most (IMPORTANT!)
				rnd y0[NWAY], cost[NWAY];		// should fit in registers
				for (int j=0; j<NWAY; j++) {
					int idx = k+i+j;	if (idx < 0) idx=0;		// don't read below data.
					y0[j] = vall(mpos_scale);
					cost[j] = vread(st, idx);		// sin(theta)
				}
				l=m;
				int ny0 = 0;
		#ifndef HI_LLIM
					do {		// sin(theta)^m
						if (l&1) for (int j=0; j<NWAY; ++j) y0[j] *= cost[j];
						for (int j=0; j<NWAY; ++j) cost[j] *= cost[j];
					} while(l >>= 1);
		#else  /* HI_LLIM */
				{	int nsint = 0;
					do {		// sin(theta)^m		(use rescaling to avoid underflow)
						if (l&1) {
							for (int j=NWAY-1; j>=0; --j) y0[j] *= cost[j];
							ny0 += nsint;
							if (vlo(y0[NWAY-1]) < (SHT_ACCURACY+1.0/SHT_SCALE_FACTOR)) {
								ny0--;
								for (int j=NWAY-1; j>=0; --j) y0[j] *= vall(SHT_SCALE_FACTOR);
							}
						}
						for (int j=NWAY-1; j>=0; --j) cost[j] *= cost[j];
						nsint += nsint;
						if (vlo(cost[NWAY-1]) < 1.0/SHT_SCALE_FACTOR) {
							nsint--;
							for (int j=NWAY-1; j>=0; --j) cost[j] *= vall(SHT_SCALE_FACTOR);
						}
					} while(l >>= 1);
				}
		#endif
				rnd y1[NWAY];
				al = alm;
				for (int j=0; j<NWAY; ++j) {
					int idx = k+i+j;	if (idx < 0) idx=0;		// don't read below data.
					cost[j] = vread(ct, idx);		// cos(theta)
					#ifndef SHTNS_ISHIOKA
					y0[j] *= vall(al[0]);
					y1[j]  = (vall(al[1])*y0[j]) * cost[j];
					#else
					cost[j] *= cost[j];		// cos(theta)^2
					y1[j] = (vall(al[1])*cost[j] + vall(al[0]))*y0[j];
					#endif
				}

				l=m;	al+=2;
		#ifdef HI_LLIM
				while ((ny0<0) && (l<lnz)) {		// ylm's are too small and are treated as zero
					#ifndef SHTNS_ISHIOKA
					for (int j=0; j<NWAY; ++j) {
						y0[j] = vall(al[1])*(cost[j]*y1[j]) + vall(al[0])*y0[j];
					}
					for (int j=0; j<NWAY; ++j) {
						y1[j] = vall(al[3])*(cost[j]*y0[j]) + vall(al[2])*y1[j];
					}
					l+=2;	al+=4;
					#else
					for (int j=0; j<NWAY; ++j) {
						rnd tmp = y1[j];
						y1[j] = (vall(al[1])*cost[j] + vall(al[0]))*y1[j] + y0[j];
						y0[j] = tmp;
					}
					l+=2;	al+=2;
					#endif
					if (fabs(vlo(y0[NWAY-1])) > SHT_ACCURACY*SHT_SCALE_FACTOR + 1.0) {		// rescale when value is significant
						++ny0;
						for (int j=0; j<NWAY; ++j) {
							y0[j] *= vall(1.0/SHT_SCALE_FACTOR);		y1[j] *= vall(1.0/SHT_SCALE_FACTOR);
						}
					}
				}
				ny[i/NWAY] = ny0;		// store extended exponents
				if ((l > llim) && (ny0<0)) break;	// nothing more to do in this block.
				lnz = l;				// record the minimum l for significant values, over this block, do not go above that afterwards
		#endif
				for (int j=0; j<NWAY; ++j) {	// store other stuff for recurrence.
					y01ct[i+j][0] = y0[j];
					y01ct[i+j][1] = y1[j];
					y01ct[i+j][2] = cost[j];
				}
			}
		#ifdef HI_LLIM
			if (ny[NBLK/NWAY-1] < 0) break;		// no ylm has a significant value in this block, the block is done.
			l = lnz;	// starting point in l for this block
		#endif

		#ifndef SHTNS_ISHIOKA
			al = alm + 2 + 2*(l-m);
			struct {
				rnd ct;
				rnd y[2];
				rnd rer, rei,  ror, roi;
			} x[NBLK];
			q+=(l-m);
			imin = (k0-k > 0) ? k0-k : 0;	// 0 <= imin < NBLK
			for (int i=imin; i<NBLK; ++i) {
				rnd w = vread(wg, k+i);		x[i].ct = y01ct[i][2];
				x[i].y[0] = y01ct[i][0] * w;	x[i].y[1] = y01ct[i][1] * w;		// weight appears here (must be after the previous accuracy loop).
				x[i].rer = vread( rer, k+i);	x[i].rei = vread( rei, k+i);	x[i].ror = vread( ror, k+i);	x[i].roi = vread( roi, k+i);
			}
			while (l<llim) {	// compute even and odd parts
				unsigned j = imin;
			#ifdef HI_LLIM
				unsigned ii = imin/NWAY;
				while ((ny[ii] < 0) && (ii<NBLK/NWAY)) {		// these are zeros
					const unsigned imax = (ii+1)*NWAY;
					do {
						rnd y0 = x[j].y[0];		rnd y1 = x[j].y[1];
						y0 = vall(al[1])*(x[j].ct*y1) + vall(al[0])*y0;
						x[j].y[0] = y0;
						x[j].y[1] = vall(al[3])*(x[j].ct*y0) + vall(al[2])*y1;
					} while (++j < imax);
					if (fabs(vlo(x[ii*NWAY+NWAY-1].y[0])) > SHT_ACCURACY*SHT_SCALE_FACTOR + 1.0) {		// rescale when value is significant
						++ny[ii];
						for (int i=0; i<NWAY; ++i) {
							x[ii*NWAY+i].y[0] *= vall(1.0/SHT_SCALE_FACTOR);		x[ii*NWAY+i].y[1] *= vall(1.0/SHT_SCALE_FACTOR);
						}
					}
					++ii;
				}
			#endif
				rnd qq0 = vall(0.0);	// real
				rnd qq1 = vall(0.0);	// imag
				rnd qq2 = vall(0.0);	// real
				rnd qq3 = vall(0.0);	// real
				while (j<NBLK) {
					register rnd y0 = x[j].y[0];
					register rnd y1 = x[j].y[1];
					{
						qq0 += y0 * x[j].rer;		qq1 += y0 * x[j].rei;	// real even, imag even
						qq2 += y1 * x[j].ror;		qq3 += y1 * x[j].roi;	// real even, imag even
					}
					y0 = vall(al[1])*(x[j].ct*y1) + vall(al[0])*y0;
					x[j].y[0] = y0;
					x[j].y[1] = vall(al[3])*(x[j].ct*y0) + vall(al[2])*y1;
					++j;
				}
				q[0] += v2d_reduce(qq0, qq1);
				q[1] += v2d_reduce(qq2, qq3);
				q+=2;
				l+=2;	al+=4;
			}
			{
				for (unsigned j=imin; j<NBLK; ++j) {
					#ifdef HI_LLIM
					if (ny[j/NWAY] == 0)
					#endif
					{
						register rnd y0 = x[j].y[0];
					}
				}
			}
			if (l==llim) {
				rnd qq0 = vall(0.0);	// real
				rnd qq1 = vall(0.0);	// imag
				for (unsigned j=imin; j<NBLK; ++j) {
					#ifdef HI_LLIM
					if (ny[j/NWAY] == 0)
					#endif
					{
						register rnd y0 = x[j].y[0];
						qq0 += y0 * x[j].rer;		qq1 += y0 * x[j].rei;	// real even, imag even
					}
				}
				for (unsigned j=imin; j<NBLK; ++j) {
					#ifdef HI_LLIM
					if (ny[j/NWAY] == 0)
					#endif
					{
						register rnd y1 = x[j].y[1];
					}
				}
				q[0] += v2d_reduce(qq0, qq1);
			}
		#else    /* SHTNS_ISHIOKA */
			al = alm + 2 + (l-m);
			struct {
				rnd y[2];
				rnd ct2;
				rnd rer, rei,  ror, roi;
			} x[NBLK];
			q+=(l-m);
			imin = (k0-k > 0) ? k0-k : 0;	// 0 <= imin < NBLK
			for (int i=imin; i<NBLK; ++i) {
				x[i].rer = vread( rer, k+i);	x[i].rei = vread( rei, k+i);	x[i].ror = vread( ror, k+i);	x[i].roi = vread( roi, k+i);
				x[i].y[0] = y01ct[i][0];		x[i].y[1] = y01ct[i][1];		x[i].ct2 = y01ct[i][2];
			}
			while (l<=llim) {	// compute even and odd parts
				unsigned i = imin;
			#ifdef HI_LLIM
				unsigned ii = imin/NWAY;
				while ((ny[ii] < 0) && (ii<NBLK/NWAY)) {		// these are zeros
					const unsigned imax = (ii+1)*NWAY;
					do {
						if (LSPAN==2) {
							rnd tmp = x[i].y[1];
							x[i].y[1] = (vall(al[1])*x[i].ct2 + vall(al[0]))*tmp + x[i].y[0];
							x[i].y[0] = tmp;
						} else {	// LSPAN == 4
							x[i].y[0] = (vall(al[1])*x[i].ct2 + vall(al[0]))*x[i].y[1] + x[i].y[0];
							x[i].y[1] = (vall(al[3])*x[i].ct2 + vall(al[2]))*x[i].y[0] + x[i].y[1];						
						}
					} while (++i < imax);
					if (fabs(vlo(x[ii*NWAY+NWAY-1].y[0])) > SHT_ACCURACY*SHT_SCALE_FACTOR + 1.0) {		// rescale when value is significant
						++ny[ii];
						for (int j=0; j<NWAY; ++j) {
							x[ii*NWAY+j].y[0] *= vall(1.0/SHT_SCALE_FACTOR);		x[ii*NWAY+j].y[1] *= vall(1.0/SHT_SCALE_FACTOR);
						}
					}
					++ii;
				}
			#endif
				rnd ql[2*LSPAN];
				for (int ll=0; ll<2*LSPAN; ll++) {
					ql[ll] = vall(0.0);
				}
				while (i<NBLK) {
					for (int ll=0; ll<LSPAN/2; ll++) {
						register rnd y = x[i].y[ll];
						ql[4*ll+0] += y * x[i].rer;		ql[4*ll+1] += y * x[i].rei;
						ql[4*ll+2] += y * x[i].ror;		ql[4*ll+3] += y * x[i].roi;
					}
					if (LSPAN==2) {
						register rnd tmp = x[i].y[1];
						x[i].y[1] = (vall(al[1])*x[i].ct2 + vall(al[0]))*tmp + x[i].y[0];
						x[i].y[0] = tmp;
					} else {	// LSPAN == 4
						x[i].y[0] = (vall(al[1])*x[i].ct2 + vall(al[0]))*x[i].y[1] + x[i].y[0];
						x[i].y[1] = (vall(al[3])*x[i].ct2 + vall(al[2]))*x[i].y[0] + x[i].y[1];						
					}
					++i;
				}
				q[0] += v2d_reduce(ql[0], ql[1]);
				for (int ll=1; ll<LSPAN; ll++) {
					if (l+ll<=llim) {
						q[ll]     += v2d_reduce(ql[2*ll], ql[2*ll+1]);
					}
					if (l+ll<=llim+1) {
					}
				}
				q+=LSPAN;
				l+=LSPAN;	al+=LSPAN;
			}
	/*		{
			}
			if (l==llim) {
		//		rnd qq0 = y0[0] * rerk[0];
		//		rnd qq1 = y0[0] * reik[0];
		//		for (int j=1; j<NW; ++j) {	qq0 += y0[j] * rerk[j];		qq1 += y0[j] * reik[j];	}	// real even, imag even
		//		q[0] += v2d_reduce(qq0, qq1);
			}	*/
		#endif
		} while (k > k0);
		
		l = LiM(shtns, m, im);
		v2d *Ql = (v2d*) &Qlm[l];

	#ifndef SHTNS_ISHIOKA
		for (l=0; l<=llim-m; ++l)	Ql[l] = qq[l];
	#else
		// post-processing for recurrence relation of Ishioka
		const double* restrict xlm = shtns->x2lm + 3*im*(2*(LMAX+4) -m+MRES)/4;
		ishioka_to_SH(xlm, qq, llim-m, Ql);
	#endif


		#ifdef SHT_VAR_LTR
			for (l=llim+1-m; l<=LMAX-m; ++l) {
				Ql[l] = vdup(0.0);
			}
		#endif
	}
  #endif
  }

	#undef BASE
	#undef LSPAN
