#!/usr/bin/env python3
import sys
import argparse
import numpy as np
import netCDF4 as nc
from datetime import datetime

def parse_tcvitals(filepath):
    """
    Parses a tcvitals text file and extracts arrays for IODA conversion.
    Based on standard TC Vitals format and the provided read_tcps.f90 logic.
    """
    lats = []
    lons = []
    times = []
    station_ids = []
    pressures = []

    with open(filepath, 'r') as f:
        for line in f:
            parts = line.split()
            if len(parts) < 11:
                continue
            
            # 1. Center and Storm ID (e.g., NHC_10E)
            center = parts[0]
            storm_id = parts[1]
            station_ids.append(f"{center}_{storm_id}")
            
            # 2. Date and Time (YYYYMMDD HHMM)
            # handle cases like ':20240924'
            date_part = parts[3].lstrip(':')
            time_part = parts[4]
            dt_str = date_part + time_part
            dt = datetime.strptime(dt_str, '%Y%m%d%H%M')
            # Convert to epoch seconds for IODA MetaData/dateTime
            epoch_sec = int((dt - datetime(1970, 1, 1)).total_seconds())
            times.append(epoch_sec)
            
            # 3. Latitude and Longitude (e.g., 169N -> 16.9, 0993W -> -99.3)
            lat_str = parts[5]
            lon_str = parts[6]
            
            lat = float(lat_str[:-1]) / 10.0
            if lat_str[-1] == 'S':
                lat = -lat
                
            lon = float(lon_str[:-1]) / 10.0
            if lon_str[-1] == 'W':
                lon = -lon
                
            lats.append(lat)
            lons.append(lon)
            
            # 4. Central Pressure (e.g., 0973 -> 973 hPa)
            # IODA standard is usually Pascals, so multiply by 100
            pmin_hpa = float(parts[9])
            pressures.append(pmin_hpa * 100.0)

    return {
        'lats': np.array(lats, dtype=np.float32),
        'lons': np.array(lons, dtype=np.float32),
        'times': np.array(times, dtype=np.int64),
        'station_ids': np.array(station_ids, dtype=object),
        'pressures': np.array(pressures, dtype=np.float32)
    }

def write_ioda_netcdf(data, out_filepath):
    """
    Writes the extracted data into an IODA-compliant NetCDF4 file.
    """
    nlocs = len(data['lats'])
    
    # Create NetCDF file
    rootgrp = nc.Dataset(out_filepath, 'w', format='NETCDF4')
    
    # 1. Global Attributes
    rootgrp.date_time = datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ')
    rootgrp.nlocs = np.int32(nlocs)
    rootgrp.history = "Generated by tcvitals2ioda.py"
    rootgrp.source = "TC Vitals"
    rootgrp._ioda_layout_version = np.int32(0)
    rootgrp._ioda_layout = "ObsGroup"
    
    # 2. Dimensions
    rootgrp.createDimension('Location', nlocs)
    
    # 3. Create Groups
    meta_grp = rootgrp.createGroup('MetaData')
    obs_grp = rootgrp.createGroup('ObsValue')
    err_grp = rootgrp.createGroup('ObsError')
    qm_grp = rootgrp.createGroup('QualityMarker')
    type_grp = rootgrp.createGroup('ObsType')

    # 4. MetaData Variables
    # Latitude
    var_lat = meta_grp.createVariable('latitude', 'f4', ('Location',))
    var_lat.units = 'degrees_north'
    var_lat.long_name = 'Latitude'
    var_lat[:] = data['lats']

    # Longitude
    var_lon = meta_grp.createVariable('longitude', 'f4', ('Location',))
    var_lon.units = 'degrees_east'
    var_lon.long_name = 'Longitude'
    var_lon[:] = data['lons']

    # station Elevation
    var_hgt = meta_grp.createVariable('stationElevation', 'f4', ('Location',))
    var_hgt.units = 'm'
    var_hgt.long_name = 'station height'
    var_hgt[:] = 0
    # Height
    var_hgt = meta_grp.createVariable('height', 'f4', ('Location',))
    var_hgt.units = 'm'
    var_hgt.long_name = 'station height'
    var_hgt[:] = 0

    # DateTime
    var_time = meta_grp.createVariable('dateTime', 'i8', ('Location',))
    var_time.units = 'seconds since 1970-01-01T00:00:00Z'
    var_time.long_name = 'Datetime'
    var_time[:] = data['times']

    # Station ID (String array)
    var_stid = meta_grp.createVariable('stationIdentification', str, ('Location',))
    var_stid.long_name = 'Station Identification'
    # For netCDF4 string variables, we write the numpy object array directly
    var_stid[:] = data['station_ids']

    # 5. ObsValue Variable (Central Pressure)
    var_pmin = obs_grp.createVariable('stationPressure', 'f4', ('Location',))
    var_pmin.units = 'Pa'
    var_pmin.long_name = 'Sea Level Pressure'
    var_pmin[:] = data['pressures']

    # 6. ObsError Variable
    # Using a default estimated error of 133 Pa (1 hPa) to mimic GSI.
    # Replace with dynamic logic based on your Fortran `tcp_ermin` and `tcp_ermax` if needed.
    var_err = err_grp.createVariable('stationPressure', 'f4', ('Location',))
    var_err.units = 'Pa'
    var_err[:] = np.full(nlocs, 75.0, dtype=np.float32)

    # 7. PreQC/QualityMarker Variable
    # 0 generally means "good" or "pass" in IODA QC conventions
    var_qc = qm_grp.createVariable('stationPressure', 'i4', ('Location',))
    var_qc[:] = np.zeros(nlocs, dtype=np.int32)

    # 8. ObsType Variable <-- Added ObsType variable mapping to 112
    var_type = type_grp.createVariable('stationPressure', 'i4', ('Location',))
    var_type.long_name = 'Observation Type'
    var_type[:] = np.full(nlocs, 112, dtype=np.int32)

    # Close file to write to disk
    rootgrp.close()
    print(f"Successfully converted {nlocs} records to IODA NetCDF: {out_filepath}")

def main():
    parser = argparse.ArgumentParser(description="Convert tcvitals text file to IODA NetCDF format.")
    parser.add_argument('input_file', type=str, help="Path to the input tcvitals file")
    parser.add_argument('output_file', type=str, help="Path to the output IODA NetCDF file")
    
    args = parser.parse_args()

    try:
        parsed_data = parse_tcvitals(args.input_file)
        if len(parsed_data['lats']) == 0:
            print("No valid tcvitals records found in the input file.")
            sys.exit(0)
            
        write_ioda_netcdf(parsed_data, args.output_file)
        
    except Exception as e:
        print(f"Error processing file: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
