#!/usr/bin/env python3
import sys
import argparse
import numpy as np
import netCDF4 as nc
from datetime import datetime

def parse_tcvitals(filepath, target_stormid=None):
    """
    Parses a tcvitals text file and extracts arrays for IODA conversion.
    Optionally filters records by a specific storm ID suffix (e.g., '09l' or '09L').
    """
    lats = []
    lons = []
    times = []
    station_ids = []
    pressures = []

    with open(filepath, 'r') as f:
        for line in f:
            parts = line.split()
            if len(parts) < 11:
                continue

            # Extract Center and Storm ID
            center = parts[0]
            storm_id = parts[1]  # e.g., '08L' or '09L'

            # Case-insensitive filter matching only the storm ID column
            if target_stormid and storm_id.upper() != target_stormid.upper():
                continue

            # Standard identifier construction for NetCDF output (e.g., 'NHC_09L')
            current_stormid = f"{center}_{storm_id}"

            date_element = next((p for p in parts if ':' in p), None)
            if date_element:
                date_part = date_element.split(':')[-1]
                idx = parts.index(date_element)
                time_part = parts[idx + 1]
                lat_str = parts[idx + 2]
                lon_str = parts[idx + 3]
                pmin_hpa = float(parts[idx + 6]) 
            else:
                # Standard case
                date_part = parts[3]
                time_part = parts[4]
                lat_str = parts[5]
                lon_str = parts[6]
                pmin_hpa = float(parts[9])

            station_ids.append(current_stormid)
            
            # Date and Time (YYYYMMDD HHMM)
            dt_str = date_part + time_part
            dt = datetime.strptime(dt_str, '%Y%m%d%H%M')
            epoch_sec = int((dt - datetime(1970, 1, 1)).total_seconds())
            times.append(epoch_sec)
            
            # Latitude and Longitude
            lat = float(lat_str[:-1]) / 10.0
            if lat_str[-1] == 'S':
                lat = -lat
                
            lon = float(lon_str[:-1]) / 10.0
            if lon_str[-1] == 'W':
                lon = -lon
                
            lats.append(lat)
            lons.append(lon)
            
            # Central Pressure
            pressures.append(pmin_hpa * 100.0)

    return {
        'lats': np.array(lats, dtype=np.float32),
        'lons': np.array(lons, dtype=np.float32),
        'times': np.array(times, dtype=np.int64),
        'station_ids': np.array(station_ids, dtype=object),
        'pressures': np.array(pressures, dtype=np.float32)
    }

def write_ioda_netcdf(data, out_filepath):
    """
    Writes the extracted data into an IODA-compliant NetCDF4 file.
    """
    nlocs = len(data['lats'])
    
    rootgrp = nc.Dataset(out_filepath, 'w', format='NETCDF4')
    
    # Global Attributes
    rootgrp.date_time = datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ')
    rootgrp.nlocs = np.int32(nlocs)
    rootgrp.history = "Generated by tcvitals2ioda.py"
    rootgrp.source = "TC Vitals"
    rootgrp._ioda_layout_version = np.int32(0)
    rootgrp._ioda_layout = "ObsGroup"
    
    # Dimensions
    rootgrp.createDimension('Location', nlocs)
    
    # Create Groups
    meta_grp = rootgrp.createGroup('MetaData')
    obs_grp = rootgrp.createGroup('ObsValue')
    err_grp = rootgrp.createGroup('ObsError')
    qm_grp = rootgrp.createGroup('QualityMarker')
    type_grp = rootgrp.createGroup('ObsType')

    # MetaData Variables
    var_lat = meta_grp.createVariable('latitude', 'f4', ('Location',))
    var_lat.units = 'degrees_north'
    var_lat.long_name = 'Latitude'
    var_lat[:] = data['lats']

    var_lon = meta_grp.createVariable('longitude', 'f4', ('Location',))
    var_lon.units = 'degrees_east'
    var_lon.long_name = 'Longitude'
    var_lon[:] = data['lons']

    var_hgt1 = meta_grp.createVariable('stationElevation', 'f4', ('Location',))
    var_hgt1.units = 'm'
    var_hgt1.long_name = 'station height'
    var_hgt1[:] = 0

    var_hgt2 = meta_grp.createVariable('height', 'f4', ('Location',))
    var_hgt2.units = 'm'
    var_hgt2.long_name = 'station height'
    var_hgt2[:] = 0

    var_time = meta_grp.createVariable('dateTime', 'i8', ('Location',))
    var_time.units = 'seconds since 1970-01-01T00:00:00Z'
    var_time.long_name = 'Datetime'
    var_time[:] = data['times']

    var_stid = meta_grp.createVariable('stationIdentification', str, ('Location',))
    var_stid.long_name = 'Station Identification'
    var_stid[:] = data['station_ids']

    # ObsValue Variable
    var_pmin = obs_grp.createVariable('stationPressure', 'f4', ('Location',))
    var_pmin.units = 'Pa'
    var_pmin.long_name = 'Sea Level Pressure'
    var_pmin[:] = data['pressures']

    # ObsError Variable
    var_err = err_grp.createVariable('stationPressure', 'f4', ('Location',))
    var_err.units = 'Pa'
    var_err[:] = np.full(nlocs, 75.0, dtype=np.float32)

    # PreQC/QualityMarker Variable
    var_qc = qm_grp.createVariable('stationPressure', 'i4', ('Location',))
    var_qc[:] = np.zeros(nlocs, dtype=np.int32)

    # ObsType Variable
    var_type = type_grp.createVariable('stationPressure', 'i4', ('Location',))
    var_type.long_name = 'Observation Type'
    var_type[:] = np.full(nlocs, 112, dtype=np.int32)

    rootgrp.close()
    print(f"Successfully converted {nlocs} records to IODA NetCDF: {out_filepath}")

def main():
    parser = argparse.ArgumentParser(description="Convert tcvitals text file to IODA NetCDF format.")
    parser.add_argument('input_file', type=str, help="Path to the input tcvitals file")
    parser.add_argument('output_file', type=str, help="Path to the output IODA NetCDF file")
    parser.add_argument('--stormid', type=str, default=None, help="Filter by storm ID suffix (e.g., 09l or 09L)")
    
    args = parser.parse_args()

    try:
        parsed_data = parse_tcvitals(args.input_file, target_stormid=args.stormid)
        if len(parsed_data['lats']) == 0:
            print(f"No valid tcvitals records found{' for storm ' + args.stormid if args.stormid else ''} in the input file.")
            sys.exit(0)
            
        write_ioda_netcdf(parsed_data, args.output_file)
        
    except Exception as e:
        print(f"Error processing file: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
