#hfsa_dev
[config]
RUN=arafs
run_wave=no
ocean_model=mom6
run_atm_init=no
run_production=no
#domlat=25.0
#domlon=-60.0
#vitalsdomlat=250N
#vitalsdomlon=600W
domlat=42.5
domlon=-140.0
vitalsdomlat=425N
vitalsdomlon=1400W

fakestormid=00E
fakestormname=EPAC
fakestormorg=NHC
fakestorm_vitals={fakestormorg} {fakestormid} {fakestormname} {YMD} {HH}{min} {vitalsdomlat} {vitalsdomlon} -99 -99 -999 -999 -099 -9 -99 -999 -999 -999 -999 M

#use GEFS input both IC abd BC
ictype=gfsgrib2ab_0p25
bctype=gfsgrib2ab_0p25

[prelaunch]
basin_overrides=no
basin_conf=none.conf
no_basin_conf=none.conf

ocean_domain=no_auto    ;; Do not choose ocean domain based on storm basin/ID
pubbasin2=ARAFS_Pac

[analysis_merge]
fwd_wave_number=2
fwd_vmax_threshold=33

[forecast]
ccpp_suite_regional=FV3_HAFS_v1_thompson_nonsst
ccpp_suite_glob=FV3_HAFS_v1_thompson_nonsst
ccpp_suite_nest=FV3_HAFS_v1_thompson_nonsst

#cpl_atm_ocn = cmeps_2way
use_oceanuv = .true.

#all_tasks=1080
#atm_tasks=1020
#ocn_tasks=60
#wav_tasks=0
#layoutx=30,20
#layouty=20,18
#write_groups=3
#write_tasks_per_group=20

all_tasks=1260
atm_tasks=1200
ocn_tasks=60
wav_tasks=0
layoutx=36,20
layouty=30,18
write_groups=3
write_tasks_per_group=40

iau_regional=.true.

progsigma=.true.
iovr=5

epbl_mstar_scheme=OM4
use_lpt=1

lim_fac=3.0
rlmx=250.
elmx=250.
sfc_rlm=1
tc_pbl=0
fhswr=900.
fhlwr=900.
clam_deep=0.15

dt_inner=45

ntrack=0
