[config]
NSTORMS=2

[forecast]
all_tasks=1920
atm_tasks=2000
# 151 is a PRIME NUMBER. If this turns out to be an issue, use slightly SLOWER layout from Bill
ocn_tasks=151

layoutx=40,20,20,20,20,20,20,20,20,20
layouty=30,20,20,20,20,20,20,20,20,20

write_groups=3
write_tasks_per_group=51
