[config]
RUN=hfsa
run_ocean=yes
run_wave=no
run_envar=yes
run_ensda=no
ENS_SIZE=80
analysis_d01=no
analysis_d02=yes
analysis_model=JEDI
direct_gdasens=NO

[prelaunch]
basin_overrides=no

[atm_init]
# ccpp suites
ccpp_suite_regional_init=FV3_HAFS_v2
ccpp_suite_glob_init=FV3_HAFS_v2
ccpp_suite_nest_init=FV3_HAFS_v2

[vi]
vi_warm_start_vmax_threshold=14
vi_pert_smth=1
vi_cloud=2

[jedi]
l4denvar=.true.
loc_h=536                ;; horizontal localization scale in km
loc_v=1.65               ;; vertical localization scale in sigma
layoutx_jedi=30
layouty_jedi=20
layoutx_gdasens=2
layouty_gdasens=2

[forecast]
# ccpp suites
ccpp_suite_regional=FV3_HAFS_v2_coupled
ccpp_suite_glob=FV3_HAFS_v2_coupled
ccpp_suite_nest=FV3_HAFS_v2_coupled

all_tasks=1080
atm_tasks=1020
ocn_tasks=60
wav_tasks=60

layoutx=30,18
layouty=20,20

dt_atmos=90
k_split=2,4
n_split=6,9
dt_inner=45
ntrack=0,4

fhswr=1800.
fhlwr=1800.
# RRTMGP
do_rrtmgp=.true.

lim_fac=2.5,2.5
rlmx=-0.055,-0.035
elmx=-0.25,-0.25
sfc_rlm=1,1
tc_pbl=0,0
fs_fac_rain=1.25
fs_fac_snow=1.25

sa3dtke_dyco=.true.
sa3dtke=.true.
tte_edmf=.false.

clam_deep=0.15
c1_deep=0.002
c1_shal=0.0005

cat_adj_deep=0.7
cat_adj_shal=0.7

pgcon_deep=0.8
pgcon_shal=0.8


# NoahMP LSM related options
lsm=2
ialb=2
iems=2

use_oceanuv=.true.

# IAU related options
iau_filter_increments=.true.
iau_delthrs=2

write_groups=3
write_tasks_per_group=20

[product]
ships_diag=.true.
