[config]
# Disable VI/DA for HAFS-C
run_atm_merge=no
run_atm_merge_fgat=no
run_atm_merge_ens=no
run_atm_vi=no
run_atm_vi_fgat=no
run_atm_vi_ens=no
run_gsi=no
gsi_d01=no
gsi_d02=no
gsi_d03=no
run_fgat=no
