[config]
RUN=hfsa
run_wave=no

[prelaunch]
basin_overrides=no

[atm_init]
# ccpp suites
ccpp_suite_regional_init=FV3_HAFS_v1_gfdlmpv3_tedmf
ccpp_suite_glob_init=FV3_HAFS_v1_gfdlmpv3_tedmf
ccpp_suite_nest_init=FV3_HAFS_v1_gfdlmpv3_tedmf

[vi]
vi_cloud=1

[forecast]
# ccpp suites
ccpp_suite_regional=FV3_HAFS_v1_gfdlmpv3_tedmf_nonsst
ccpp_suite_glob=FV3_HAFS_v1_gfdlmpv3_tedmf_nonsst
ccpp_suite_nest=FV3_HAFS_v1_gfdlmpv3_tedmf_nonsst

# GFDL MP related options
imp_physics=11
dnats=1
do_sat_adj=.true.
lgfdlmprad=.true.

all_tasks=960
atm_tasks=900
ocn_tasks=60
wav_tasks=60
layoutx=30,20
layouty=20,12

sa3dtke_dyco=.true.
sa3dtke=.true.

write_groups=3
write_tasks_per_group=20
