[config]
RUN=hfsa
run_ocean=yes
run_wave=yes
run_envar=yes
run_ensda=yes
run_atm_init=yes
run_atm_init_ens=no
ENS_SIZE=40
GRID_RATIO_ENS=3
NHRS_ENS=9
NBDYHRS_ENS=3
NOUTHRS_ENS=3

[atm_init]
layoutx_init=16,12
layouty_init=16,8

write_groups_init=1
write_tasks_per_group_init=32

[forecast]
all_tasks=1024
atm_tasks=768
ocn_tasks=128
wav_tasks=128
layoutx=32,16
layouty=16,12
write_groups=2
write_tasks_per_group=32

[grid_ens]
nest_grids_ens=1
refine_ratio_ens=3
istart_nest_ens=293
jstart_nest_ens=293
iend_nest_ens=732
jend_nest_ens=732
idim_nest_ens=660
jdim_nest_ens=660
delx_nest_ens=0.027
dely_nest_ens=0.027

[forecast_ens]
all_tasks_ens=96
atm_tasks_ens=96
layoutx_ens=10
layouty_ens=9
npx_ens=661
npy_ens=661

#stochastic physics related options
do_sppt_ens=.false.
do_shum_ens=.false.
do_skeb_ens=.false.

is_moving_nest_ens=.false.,.false.
restart_interval_ens="3 6 9"
write_groups_ens=1
write_tasks_per_group_ens=6

output_grid_lon_span_ens=39.6
output_grid_lat_span_ens=39.6
