[config]
RUN=hfsa
run_wave=no
analysis_model=GSI

[prelaunch]
#basin_overrides=no

[atm_init]
# ccpp suites
ccpp_suite_regional_init=FV3_HAFS_v2
ccpp_suite_glob_init=FV3_HAFS_v2
ccpp_suite_nest_init=FV3_HAFS_v2

[vi]
vi_warm_start_vmax_threshold=14
vi_pert_smth=1
vi_cloud=2

[gsi]
s_ens_h=300,100,120
tdr_superob=.true.

[forecast]
# ccpp suites
ccpp_suite_regional=FV3_HAFS_v2_coupled
ccpp_suite_glob=FV3_HAFS_v2_coupled
ccpp_suite_nest=FV3_HAFS_v2_coupled

all_tasks=1080
atm_tasks=1020
ocn_tasks=60
wav_tasks=60

layoutx=30,18
layouty=20,20

dt_atmos=90
k_split=2,4
n_split=5,9
dt_inner=45
ntrack=0,4

fhswr=1800.
fhlwr=1800.
# RRTMGP
do_rrtmgp=.true.

lim_fac=3.0,3.0
rlmx=-0.055,-0.035
elmx=-0.25,-0.25
sfc_rlm=1,1
tc_pbl=0,0
fs_fac_rain=1.25
fs_fac_snow=1.25

sa3dtke_dyco=.true.
sa3dtke=.true.
tte_edmf=.false.

clam_deep=0.15
c1_deep=0.0001
c1_shal=0.0001

cat_adj_deep=0.85
cat_adj_shal=0.85

# NoahMP LSM related options
lsm=2
ialb=2
iems=2

use_oceanuv=.true.

# IAU related options
iau_filter_increments=.true.
iau_delthrs=2

write_groups=3
write_tasks_per_group=20

[product]
ships_diag=.true.

