[config]
RUN=hfsa
run_wave=no
run_atm_mvnest=no

run_atm_init=no
run_atm_init_fgat=no
run_atm_init_ens=no

run_atm_merge=no
run_atm_merge_fgat=no
run_atm_merge_ens=no

run_atm_vi=no
run_atm_vi_fgat=no
run_atm_vi_ens=no

run_analysis=yes
analysis_model=JEDI
analysis_d01=yes
analysis_d02=no
run_fgat=yes
run_envar=yes
run_ensda=yes
run_enkf=yes

run_analysis_merge=no

NHRS=12
ENS_SIZE=40
GRID_RATIO_ENS=3
NHRS_ENS=9
NBDYHRS_ENS=3
NOUTHRS_ENS=3

domlat=30.0
domlon=-65.0
vitalsdomlat=300N
vitalsdomlon=650W
fakestormid=00L
fakestormname=NATL
fakestormorg=NHC
fakestorm_vitals={fakestormorg} {fakestormid} {fakestormname} {YMD} {HH}{min} {vitalsdomlat} {vitalsdomlon} -99 -99 -999 -999 -099 -9 -99 -999 -999 -999 -999 M

[prelaunch]
basin_overrides=no

[jedi]
l4denvar=.true.
loc_h=536             ;; horizontal localization scale in km
loc_v=1.65            ;; vertical localization scale in sigma
layoutx_jedi=30
layouty_jedi=20
layoutx_enkf=30
layouty_enkf=20
bump_resolution=4
dlon_cutoff=120
dlat_cutoff=60 		  ;; Data domain cut for DA efficiency, degrees relative to domain center

[grid]
CASE=C512            ;; FV3 resolution
LEVS=82              ;; Model vertical levels: 65
gtype=regional       ;; grid type: uniform, stretch, nest, or regional
# If gridfixdir is provided and the dir exists, then the hafs_grid job will
# just copy over the pre-generated static grid fix files under the gridfixdir.
#gridfixdir={FIXhafs}/fix_fv3/grid_300N650W_3900x2700_2p4km/C512
stretch_fac=1.0001   ;; Stretching factor for the grid
target_lon={domlon}  ;; center longitude of the highest resolution tile
target_lat={domlat}  ;; center latitude of the highest resolution tile
nest_grids=1
parent_grid_num=1
parent_tile=6
refine_ratio=6       ;; specify the refinement ratio for nest grid
istart_nest=133      ;; start index of the regional/nested domain on the tile's super grid
jstart_nest=143
iend_nest=1432       ;; end index of the regional/nested domain on the tile's super grid
jend_nest=1042
halo=3               ;; halo size to be used in the atmosphere cubic sphere model for the grid tile.
halop1=4             ;; halo size that will be used for the orography and grid tile in chgres
halo0=0              ;; no halo, used to shave the filtered orography for use in the model
regional_esg=yes     ;; Use regional ESG grid, yes, or no
idim_nest=3900
jdim_nest=2700
delx_nest=0.012
dely_nest=0.012
halop2=15
pazi=-180.

[forecast]
all_tasks=3000
atm_tasks=2820
ocn_tasks=180

layoutx=60
layouty=45

npx=3901
npy=2701

dt_atmos=90
k_split=3
n_split=10

fhswr=1800.
fhlwr=1800.

is_moving_nest=.false.

# IAU related options
iau_regional=.false.

restart_fh="240"

write_groups=2
write_tasks_per_group=60

output_grid=regional_latlon
output_grid_cen_lon=-65.0
output_grid_cen_lat=26.5
output_grid_lon_span=126.0
output_grid_lat_span=57.0
output_grid_dlon=0.025
output_grid_dlat=0.025

[grid_ens]
#gridfixdir_ens={FIXhafs}/fix_fv3/grid_ens_300N650W_1300x900_7p2km/C512
nest_grids_ens=1
refine_ratio_ens=2
istart_nest_ens=133
jstart_nest_ens=143
iend_nest_ens=1432
jend_nest_ens=1042
delx_nest_ens=0.036
dely_nest_ens=0.036
idim_nest_ens=1300
jdim_nest_ens=900
halop2_ens=5

[forecast_ens]
ccpp_suite_regional_ens=FV3_HAFS_v2
ccpp_suite_glob_ens=FV3_HAFS_v2
ccpp_suite_nest_ens=FV3_HAFS_v2
nstf_n1_ens=2
nstf_n2_ens=0
nstf_n3_ens=0
nstf_n4_ens=0
nstf_n5_ens=0

all_tasks_ens=360
layoutx_ens=20
layouty_ens=15

npx_ens=1301
npy_ens=901

k_split_ens=2
n_split_ens=5

write_groups_ens=3
write_tasks_per_group_ens=20

#stochastic physics related options
do_sppt_ens=.true.
do_shum_ens=.true.
do_skeb_ens=.true.

output_grid_dlon_ens=0.075
output_grid_dlat_ens=0.075

