[config]
RUN=hfsa
run_wave=no
domlon=-80.
domlat=15.

rrfs_recenter=yes
run_envar=yes
run_ensda=yes
run_enkf=yes
ENS_SIZE=4
GRID_RATIO_ENS=3
NHRS_ENS=9
NBDYHRS_ENS=3
NOUTHRS_ENS=3
analysis_d01=yes
analysis_d02=no
run_atm_mvnest=no
analysis_model=JEDI

[prelaunch]
basin_overrides=no

[atm_init]
# ccpp suites
ccpp_suite_regional_init=FV3_HAFS_v2
ccpp_suite_glob_init=FV3_HAFS_v2
ccpp_suite_nest_init=FV3_HAFS_v2
layoutx_init=20
layouty_init=15

[vi]
vi_warm_start_vmax_threshold=14
vi_pert_smth=1
vi_cloud=2

[gsi]
s_ens_h=300,100,120
tdr_superob=.true.

[jedi]
l4denvar=.true.
loc_h=536                ;; horizontal localization scale in km
loc_v=1.65               ;; vertical localization scale in sigma
layoutx_jedi=40
layouty_jedi=25
layoutx_enkf=30
layouty_enkf=20
bump_resolution=4
dlon_cutoff=60
dlat_cutoff=40 		  ;; Data Domain Cut for DA efficiency, degres relative to the domain center. Only those data will be considered for pre/prior filters to save time.

[grid]
nest_grids=1
refine_ratio=3
istart_nest=33
jstart_nest=73
iend_nest=992
jend_nest=952
idim_nest=1440
jdim_nest=1320
delx_nest=0.027
dely_nest=0.027

[forecast]
# ccpp suites
ccpp_suite_regional=FV3_HAFS_v2_coupled
ccpp_suite_glob=FV3_HAFS_v2_coupled
ccpp_suite_nest=FV3_HAFS_v2_coupled

all_tasks=720
atm_tasks=600
ocn_tasks=60
wav_tasks=60

npx=1441
npy=1321

layoutx=30
layouty=20

dt_atmos=90
k_split=2
n_split=5
dt_inner=45
ntrack=0,4

fhswr=1800.
fhlwr=1800.
# RRTMGP
do_rrtmgp=.true.

lim_fac=3.0
rlmx=-0.055
elmx=-0.25
sfc_rlm=1
tc_pbl=0
fs_fac_rain=1.25
fs_fac_snow=1.25

sa3dtke_dyco=.true.
sa3dtke=.true.
tte_edmf=.false.

clam_deep=0.15
c1_deep=0.0001
c1_shal=0.0001

cat_adj_deep=0.85
cat_adj_shal=0.85

# NoahMP LSM related options
lsm=2
ialb=2
iems=2

use_oceanuv=.true.

# IAU related options
iau_filter_increments=.true.
iau_delthrs=2

write_groups=3
write_tasks_per_group=20

is_moving_nest=.false.

[product]
ships_diag=.true.

[grid_ens]
nest_grids_ens=1
refine_ratio_ens=1
istart_nest_ens=31
jstart_nest_ens=71
iend_nest_ens=994
jend_nest_ens=954
delx_nest_ens=0.081
dely_nest_ens=0.081
idim_nest_ens=482
jdim_nest_ens=442

[forecast_ens]
ccpp_suite_regional_ens=FV3_HAFS_v2
ccpp_suite_glob_ens=FV3_HAFS_v2
ccpp_suite_nest_ens=FV3_HAFS_v2

all_tasks_ens=360
layoutx_ens=16
layouty_ens=20
write_groups_ens=2
write_tasks_per_group_ens=20
npx_ens=482
npy_ens=442

nstf_n1_ens=2
nstf_n2_ens=0
nstf_n3_ens=0
nstf_n4_ens=0
nstf_n5_ens=0
is_moving_nest_ens=.false.
restart_interval_ens="3 6 9"

[rocotostr]
FORECAST_ENS_RESOURCES=FORECAST_RESOURCES_360PE
