## hafs_input.conf
## Configures input sources for the HAFS system

# This file is read in after the hafs.conf file, and specifies where
# to get input data.

[wcoss_fcst_nco]
messages={ENV[COMINmsg]}/                                      ;; Hurricane message file directory
syndatdir={ENV[COMINarch]}                                     ;; TCVitals directory
gfs={ENV[COMINgfs]}/gfs.{aYMD}/{aHH}/products/atmos/grib2/0p25 ;; GFS 0p25 grib2 file directory
gfswave={ENV[COMINgfs]}/gfs.{aYMD}/{aHH}/products/wave/station ;; gfswave root directory for wave boundary condition
gdaswave={ENV[COMINgdas]}/gdas.{aYMD}/{aHH}/model/wave/restart ;; gdaswave root directory for wave initial condition
gfs_gribA=gfs.t{aHH}z.pres_a.0p25.f{fahr:03d}.grib2            ;; GFS GRIB on standard levels
ww3bdy_ibp=gfs.t{aHH}z.ibp.tar                                 ;; gfswave wave boundary file
ww3rst_gnh_10m={ap6YMD}.{ap6HH}0000.restart.ww3.nc             ;; gdaswave wave initial condition file

[fcst_PROD2021]
messages={COMINmsg}/                                           ;; Hurricane message file directory
syndatdir={COMINarch}/                                         ;; TCVitals directory
gfs={COMINgfs}/gfs.{aYMD}/{aHH}/atmos/                         ;; GFS 0p25 grib2 file directory
gfswave={COMINgfs}/gfs.{aYMD}/{aHH}/wave/station               ;; gfswave root directory for wave boundary condition
gdaswave={COMINgdas}/gdas.{aYMD}/{aHH}/wave/restart            ;; gdaswave root directory for wave initial condition
gfs_gribA=gfs.t{aHH}z.pgrb2.0p25.f{fahr:03d}                   ;; GFS GRIB on standard levels
ww3bdy_ibp=gfswave.t{aHH}z.ibp_tar                             ;; gfswave wave boundary file
ww3rst_gnh_10m={ap6YMD}.{ap6HH}0000.restart.gnh_10m            ;; gdaswave wave initial condition file

[fcst_PROD2026]
messages={COMINmsg}/                                           ;; Hurricane message file directory
syndatdir={COMINarch}/                                         ;; TCVitals directory
gfs={COMINgfs}/gfs.{aYMD}/{aHH}/products/atmos/grib2/0p25      ;; GFS 0p25 grib2 file directory
gfswave={COMINgfs}/gfs.{aYMD}/{aHH}/products/wave/station      ;; gfswave directory for wave boundary condition
gdaswave={COMINgdas}/gdas.{aYMD}/{aHH}/model/wave/restart      ;; gdaswave directory for wave initial condition
gfs_gribA=gfs.t{aHH}z.pres_a.0p25.f{fahr:03d}.grib2            ;; GFS GRIB on standard levels
ww3bdy_ibp=gfs.t{aHH}z.ibp.tar                                 ;; gfswave wave boundary file
ww3rst_gnh_10m={ap6YMD}.{ap6HH}0000.restart.ww3.nc             ;; gdaswave wave initial condition file
