[config]
RUN=hfsa
run_wave=no

[prelaunch]
basin_overrides=no

[atm_init]
# ccpp suites
ccpp_suite_regional_init=FV3_HAFS_v2
ccpp_suite_glob_init=FV3_HAFS_v2
ccpp_suite_nest_init=FV3_HAFS_v2

[vi]
vi_warm_start_vmax_threshold=20
vi_pert_smth=1
vi_cloud=2

[gsi]
s_ens_h=300,100,120
tdr_superob=.true.

[forecast]
# ccpp suites
ccpp_suite_regional=FV3_HAFS_v2_coupled
ccpp_suite_glob=FV3_HAFS_v2_coupled
ccpp_suite_nest=FV3_HAFS_v2_coupled

all_tasks=1080
atm_tasks=1020
ocn_tasks=60
wav_tasks=60

layoutx=30,20
layouty=20,18

dt_atmos=90
k_split=2,4
n_split=5,9
dt_inner=45
ntrack=0,4

fhswr=900.
fhlwr=900.
# RRTMGP
do_rrtmgp=.true.

lim_fac=3.0,3.0
rlmx=300.,250.
elmx=300.,250.
sfc_rlm=1,1
tc_pbl=0,0

sa3dtke_dyco=.true.
sa3dtke=.true.
tte_edmf=.false.

clam_deep=0.15
c1_deep=0.0001
c1_shal=0.0001

# NoahMP LSM related options
lsm=2
ialb=2
iems=2

use_oceanuv=.true.
#cpl_wav_ocn=cmeps_1way_2to1

write_groups=3
write_tasks_per_group=20
