[config]
RUN=hfsa
run_ocean=yes
run_wave=no
run_envar=yes
run_ensda=yes
run_atm_init=yes
run_atm_init_ens=no
ENS_SIZE=40
GRID_RATIO_ENS=3
NHRS_ENS=9
NBDYHRS_ENS=3
NOUTHRS_ENS=3

[gsi]
l_both_fv3sar_gfs_ens=.true. ;; Whether or not use both gdas and regional ensembles in GSI EnVar analysis

[forecast]
all_tasks=960
atm_tasks=900
ocn_tasks=60
wav_tasks=60
layoutx=30,20
layouty=20,12
write_groups=3
write_tasks_per_group=20

[grid_ens]
nest_grids_ens=1
refine_ratio_ens=3
istart_nest_ens=313
jstart_nest_ens=313
iend_nest_ens=712
jend_nest_ens=712
idim_nest_ens=600
jdim_nest_ens=600
delx_nest_ens=0.027
dely_nest_ens=0.027

[forecast_ens]
# ccpp suites
ccpp_suite_regional_ens=FV3_HAFS_v1_thompson
ccpp_suite_glob_ens=FV3_HAFS_v1_thompson
ccpp_suite_nest_ens=FV3_HAFS_v1_thompson

# nsst related namelist options
# Choose nstf_name=2,0,0,0,0 when nemsio type ictype
# Choose nstf_name=2,1,0,0,0 when grib2 type ictype
nstf_n1_ens=2
nstf_n2_ens=0
nstf_n3_ens=0
nstf_n4_ens=0
nstf_n5_ens=0

all_tasks_ens=120
layoutx_ens=11
layouty_ens=10
write_groups_ens=1
write_tasks_per_group_ens=10

npx_ens=601
npy_ens=601

#stochastic physics related options
do_sppt_ens=.false.
do_shum_ens=.false.
do_skeb_ens=.false.

is_moving_nest_ens=.false.,.false.
restart_interval_ens="3 6 9"

output_grid_lon_span_ens=36.0
output_grid_lat_span_ens=36.0
