[config]
RUN=hfsa
run_ocean=yes
run_wave=yes
run_envar=yes
run_ensda=yes
run_atm_init=yes
run_atm_init_ens=no
ENS_SIZE=40
GRID_RATIO_ENS=3
NHRS_ENS=9
NBDYHRS_ENS=3
NOUTHRS_ENS=3

[prelaunch]
basin_overrides=no

[atm_init]
# ccpp suites
ccpp_suite_regional_init=FV3_HAFS_v1_gfdlmpv3_noahmp
ccpp_suite_glob_init=FV3_HAFS_v1_gfdlmpv3_noahmp
ccpp_suite_nest_init=FV3_HAFS_v1_gfdlmpv3_noahmp

[vi]
vi_warm_start_vmax_threshold=17
vi_pert_smth=1
vi_cloud=1

[gsi]
l_both_fv3sar_gfs_ens=.false. ;; Whether or not use both gdas and regional ensembles in GSI EnVar analysis
tdr_superob=.true.            ;; Turn on/off superobbing for TDR observations

[forecast]
# ccpp suites
ccpp_suite_regional=FV3_HAFS_v1_gfdlmpv3_noahmp_nonsst
ccpp_suite_glob=FV3_HAFS_v1_gfdlmpv3_noahmp_nonsst
ccpp_suite_nest=FV3_HAFS_v1_gfdlmpv3_noahmp_nonsst

all_tasks=1020
atm_tasks=900
ocn_tasks=60
wav_tasks=60
layoutx=30,20
layouty=20,12

dt_atmos=72
k_split=2,4
n_split=4,9
dt_inner=36

fhswr=720.
fhlwr=720.
ntrack=0,5

sa3dtke_dyco=.true.
sa3dtke=.true.
tte_edmf=.true.

cpl_wav_ocn=cmeps_1way_2to1

# GFDL MP related options
imp_physics=11
dnats=1
do_sat_adj=.true.
lgfdlmprad=.true.

# Noah LSM related options
lsm=2
ialb=2
iems=2

write_groups=3
write_tasks_per_group=20

[grid_ens]
nest_grids_ens=1
refine_ratio_ens=3
istart_nest_ens=313
jstart_nest_ens=313
iend_nest_ens=712
jend_nest_ens=712
idim_nest_ens=600
jdim_nest_ens=600
delx_nest_ens=0.027
dely_nest_ens=0.027

[forecast_ens]
# ccpp suites
ccpp_suite_regional_ens=FV3_HAFS_v1_gfdlmpv3_noahmp
ccpp_suite_glob_ens=FV3_HAFS_v1_gfdlmpv3_noahmp
ccpp_suite_nest_ens=FV3_HAFS_v1_gfdlmpv3_noahmp

# nsst related namelist options
# Choose nstf_name=2,0,0,0,0 when nemsio type ictype
# Choose nstf_name=2,1,0,0,0 when grib2 type ictype
nstf_n1_ens=2
nstf_n2_ens=0
nstf_n3_ens=0
nstf_n4_ens=0
nstf_n5_ens=0

all_tasks_ens=120
layoutx_ens=11
layouty_ens=10
write_groups_ens=1
write_tasks_per_group_ens=10

npx_ens=601
npy_ens=601

#stochastic physics related options
do_sppt_ens=.false.
do_shum_ens=.false.
do_skeb_ens=.false.

is_moving_nest_ens=.false.,.false.
restart_interval_ens="3 6 9"

output_grid_lon_span_ens=36.0
output_grid_lat_span_ens=36.0
