[config]
RUN=hfsa
run_wave=no

[prelaunch]
basin_overrides=no

[vi]
vi_warm_start_vmax_threshold=14
vi_pert_smth=1

[forecast]
all_tasks=960
atm_tasks=900
ocn_tasks=60
wav_tasks=60
layoutx=30,20
layouty=20,12

sa3dtke_dyco=.true.
sa3dtke=.true.

write_groups=3
write_tasks_per_group=20
