[config]
RUN=hfsa
run_wave=no
run_ocean=no
run_atm_init_ens=yes
ENS_SIZE=40
analysis_d01=no
analysis_d02=yes
analysis_model=JEDI
run_atm_init_fgat=no
run_atm_vi_fgat=no
run_fgat=no
run_ensda=no
GRID_RATIO_ENS=3

[gsi]
l4densvar=.false.

[jedi]
l4denvar=.false.
loc_h=250                ;; horizontal localization scale in km
loc_v=0.01               ;; vertical localization scale in sigma


[grid_ens]
gridfixdir_ens={grid/gridfixdir}
regional_esg_ens={grid/regional_esg}
nest_grids_ens=1
refine_ratio_ens=3
idim_nest_ens=1440
jdim_nest_ens=1420
delx_nest_ens=0.027
dely_nest_ens=0.027

[forecast]
all_tasks=1080
atm_tasks=1020
ocn_tasks=60
wav_tasks=60
layoutx=30,21
layouty=20,20

write_groups=3
write_tasks_per_group=20

[forecast_ens]
dt_atmos_ens=90
npx_ens=1441
npy_ens=1321

[rocotostr]
FORECAST_ENS_RESOURCES=FORECAST_RESOURCES_660PE
