## The default configuration (all options enabled) will be the AL
## configuration. However, this file MUST exist otherwise the
## parm/hfsb_other_basins.conf will be used.
[atm_init]
# ccpp suites
ccpp_suite_regional_init=FV3_HAFS_v2_gfdlmp
ccpp_suite_glob_init=FV3_HAFS_v2_gfdlmp
ccpp_suite_nest_init=FV3_HAFS_v2_gfdlmp

[vi]
vi_cloud=1

[forecast]

# ccpp suites
ccpp_suite_regional=FV3_HAFS_v2_gfdlmp_coupled
ccpp_suite_glob=FV3_HAFS_v2_gfdlmp_coupled
ccpp_suite_nest=FV3_HAFS_v2_gfdlmp_coupled

k_split=3,4
n_split=4,8
lim_fac=3.0,3.0
fhswr=1800.
fhlwr=1800.

# GFDL MP related options
imp_physics=11
dnats=1
do_sat_adj=.true.
lgfdlmprad=.true.
