## The default configuration (all options enabled) will be the AL
## configuration. However, this file MUST exist otherwise the
## parm/hfsb_other_basins.conf will be used.
[forecast]
lim_fac=3.0,3.0
