#=======================================================================

#$$$ MAKEFILE DOCUMENTATION BLOCK

# Copyright (C) 2019 Henry R. Winterbottom

# Email: henry.winterbottom@noaa.gov

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

# Review the README, within the top-level directory, which provides
# relevant instructions and (any) references cited by algorithms
# within this software suite.

#=======================================================================

# Fortran compiler and options

LD              = $(FC)
LDFLAGS         = $(FCFFLAGS)

# Library dependencies

LIBbacio        = -L$(BACIO)/lib -lbacio
LIBfson         = -L$(FSON)/lib -lfson
LIBgridprojs    = -L$(GRIDPROJS)/lib -lgridprojs
LIBnemsio       = -L$(NEMSIO)/lib -lnemsio
LIBnetcdf       = -L$(NETCDF)/lib -lnetcdff
LIBslint        = -L$(SLINT)/lib -lslint
LIBw3           = -L$(W3)/lib -lw3
LIBS            = $(LIBfson) $(LIBgridprojs) $(LIBnemsio) $(LIBnetcdf) $(LIBslint) $(LIBw3) $(LIBbacio)

# Module dependencies

INCbacio        = -I$(BACIO)/include
INCfson         = -I$(FSON)/include
INCgridprojs    = -I$(GRIDPROJS)/include
INCnemsio       = -I$(NEMSIO)/include
INCnetcdf       = -I$(NETCDF)/include
INCslint        = -I$(SLINT)/include
INCS            = $(INCfson) $(INCgridprojs) $(INCnemsio) $(INCnetcdf) $(INCslint) $(INCbacio)

# Executable

EXEC            = post_utils.x

# Source files

SRCSF90         = kinds_interface.F90 \
                  constants_interface.F90 \
                  diagnostics_interface.F90 \
		  namelist_interface.F90 \
		  variable_interface.F90 \
		  json_interface.F90 \
		  nemsio_interface.F90 \
		  netcdf_interface.F90 \
		  fileio_interface.F90 \
		  interpolation_interface.F90 \
		  grid_methods_interface.F90 \
		  fv3_post_interface.F90 \
		  post_utils_interface.F90

SRCSF77         =