#!/bin/sh

set -xe

date
source ${USHhafs}/hafs_pre_job.sh.inc
HOLDVARS=${HOLDVARS:-/can/not/find/storm1.holdvars.txt}
source ${HOLDVARS}

export EXPT=${EXPT:-HAFS}
export SUBEXPT=${SUBEXPT:-${EXPT}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:-00}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}

export NHRS=${NHRS:-126}
export NBDYHRS=${NBDYHRS:-3}
export CASE=${CASE:-C768}
export CRES=`echo $CASE | cut -c 2-`
export gtype=${gtype:-regional}           # grid type = uniform, stretch, nest, or stand alone regional
export ictype=${ictype:-gfsnemsio} # gfsnemsio
export bctype=${bctype:-gfsnemsio} # gfsnemsio, gfsgrib2_master, gfsgrib2_0p25, gfsgrib2_0p50, gfsgrib2_1p00
export LEVS=${LEVELS:-65}
export NTRAC=7			# output all gfdl mp tracers

if [ "${gtype}" != "regional" ]; then
  echo "INFO: ${gtype} not a regional run."
  echo "INFO: No need to run chgres_bc."
  echo "INFO: Exitting."
  exit
fi

####################################
# Specify Execution Areas
####################################
export HOMEhafs=${HOMEhafs:-/gpfs/hps3/emc/hwrf/noscrub/${USER}/save/HAFS}
export WORKhafs=${WORKhafs:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/${CDATE}/${STORMID}}
export COMIN=${COMIN:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMOUT=${COMOUT:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMhafs=${COMhafs:-${COMOUT}}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

export WGRIB2=${WGRIB2:-wgrib2}
export CHGRESCUBEEXEC=${EXEChafs}/hafs_chgres_cube.x

####################################
# Load Modules if Needed
####################################
export machine=${WHERE_AM_I:-wcoss_cray} # platforms: wcoss_cray, wcoss_dell_p3, hera, orion, jet
#export RUN_ENVIR=${RUN_ENVIR:-prod}
export RUN_ENVIR=${envir:-prod}
if [ "$RUN_ENVIR" = prod ]; then
  #module use ${HOMEhafs}/modulefiles
  #module load modulefile.hafs.run.${machine}
  module list
fi

#####################################
# Set up job node/core/run environment variables
#####################################
source ${USHhafs}/hafs_runcmd.sh.inc

####################################
# Run setpdy and initialize PDY variables
####################################
#setpdy.sh
#. ./PDY

PDYtmp=$(echo ${YMDH} | cut -c 1-8 )
export PDY=${PDY:-${PDYtmp}}

#####################################
# Working directories
#####################################
export BC_GROUPN=${BC_GROUPN:-6}
export BC_GROUPI=$( printf "%03d" "${BC_GROUPI:-001}" )

export OUTDIR=${OUTDIR:-${WORKhafs}/intercom/chgres}
export DATA=${WORKhafs}/chgres_bc${BC_GROUPI}

export SCRUBDATA=${SCRUBDATA:-YES}

if [ "${SCRUBDATA}" = YES ]; then
  rm -rf $DATA
fi

mkdir -p $OUTDIR $DATA
cd $DATA

#####################################
# Define COM directories
#####################################
#export COMROOT=${COMROOT:-/gpfs/hps/nco/ops/com}
#export COMgfs=${COMgfs:-/${COMROOT}/gfs/prod}
export COMgfs=${COMgfs:-/gpfs/dell1/nco/ops/com/gfs/para}
export INIDIR=${COMgfs}/gfs.$PDY/$cyc

#####################################
# Generate the BCs
#####################################
export REGIONAL=2

export FHRB=$(( ${BC_GROUPI} * ${NBDYHRS} ))
export FHRI=$(( ${BC_GROUPN} * ${NBDYHRS} ))
export FHRE=${NHRS}

#####################################
# Execute the script.
${HOMEhafs}/scripts/exhafs_chgres_bc.sh
export err=$?
#####################################

exit
