#!/bin/sh

date
export PS4='+ $SECONDS + '
set -xue

export cycle=${cycle:-t${cyc:?}z}
export hafs_ver=${hafs_ver:-v1.0}
export NET=${NET:-hafs}
export RUN=${RUN:-hfsa}
export envir=${envir:-test}
export RUN_ENVIR=${RUN_ENVIR:-DEV}

export EMAIL_SDM=${EMAIL_SDM:-NO}
export HAFS_EMAIL_FROM=${HAFS_EMAIL_FROM:-"nco.spa@noaa.gov"}
export HAFS_SDM_EMAIL_LIST=${HAFS_SDM_EMAIL_LIST:-"sdm@noaa.gov"}

export HOMEhafs=${HOMEhafs:-${OPSROOT:?}/hafs.${hafs_ver:?}}
export USHhafs=$HOMEhafs/ush
export EXEChafs=$HOMEhafs/exec
export PARMhafs=$HOMEhafs/parm
export FIXhafs=$HOMEhafs/fix

# Prepend $USHhafs to python package search path
export PYTHONPATH=$USHhafs${PYTHONPATH:+:$PYTHONPATH}

export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

# Initialize PDY
setpdy.sh
# Get PDY
. ./PDY

export COMINnhc=${COMINnhc:-${DCOMROOT}/nhc/atcf/ncep}
export COMINjtwc=${COMINjtwc:-${DCOMROOT}/${PDY}/wtxtbul/storm_data}
export COMINmsg=${COMINmsg:-$(compath.py ${envir}/${NET}/${hafs_ver})/inp${RUN}}

# Execute ex-script
${HOMEhafs}/scripts/exhafs_msg_check.py "${PDY:2:6}" "$cyc"
status=$?; [[ $status -ne 0 ]] && exit $status

# Cleanup DATA dir
cd ${DATAROOT}
if [ "${KEEPDATA:-YES}" != "YES" ]; then
  rm -rf $DATA
fi

date
