#!/bin/sh

date
export PS4='+ $SECONDS + '
set -xue

export HOMEhafs=${HOMEhafs:?}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

source ${USHhafs}/hafs_pre_job.sh.inc
source ${HOLDVARS:-storm1.holdvars.txt}

export machine=${WHERE_AM_I:-wcoss2}
export envir=${envir:-prod} # prod, para, test
export RUN_ENVIR=${RUN_ENVIR:-dev} # nco or dev
if [ "${RUN_ENVIR^^}" != NCO ]; then
  module use ${HOMEhafs}/sorc/hafs_post.fd/modulefiles
# module load ${machine}
  module list
fi

source ${USHhafs}/hafs_runcmd.sh.inc

# Run setpdy and initialize PDY variables
#setpdy.sh
#. ./PDY
export PDY=${PDY:-$(echo ${YMDH} | cut -c 1-8 )}

export WORKhafs=${WORKhafs:?}
export COMIN=${COMIN:?}
export COMOUT=${COMOUT:?}
export COMhafs=${COMhafs:-${COMOUT}}
export FIXcrtm=${FIXcrtm:-${CRTM_FIX:?}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:?}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}
export FAKESTORMID=${FAKESTORMID:-00L}
export ENSDA=${ENSDA:-NO}

# Ghassan.Alaka@noaa.gov 2024-01-09
# Add multistorm env vars
export RUN_MULTISTORM=${RUN_MULTISTORM:-NO}
# Lew.Gramer@noaa.gov 2024-02-23: tweaked search and replace
export FAKEWORKhafs=${FAKEWORKhafs:-$(echo "${WORKhafs/\/${STORMID}//${FAKESTORMID}}")}
# GJA

# Deterministic or ensemble
if [ ${ENSDA} = YES ]; then
  export ENSID=${ENSID:-001}
  export INPdir=${INPdir:-${WORKhafs}/forecast_ens/mem${ENSID}}
  export DATA=${WORKhafs}/atm_post_ens/mem${ENSID}
  export COMOUTpost=${COMhafs}/post_ens/mem${ENSID}
  export intercom=${WORKhafs}/intercom/post_ens/mem${ENSID}
# Ghassan.Alaka@noaa.gov 2024-01-09
# Add a new IF branch to check the fake storm directory for the
# forecast outputs when running multistorm.
elif [ ${RUN_MULTISTORM} = YES ]; then
  export INPdir=${INPdir:-${FAKEWORKhafs}/forecast}
  export DATA=${WORKhafs}/atm_post
  export COMOUTpost=${COMhafs}
  export intercom=${WORKhafs}/intercom/post
# GJA
else
  export INPdir=${INPdir:-${WORKhafs}/forecast}
  export DATA=${WORKhafs}/atm_post
  export COMOUTpost=${COMhafs}
  export intercom=${WORKhafs}/intercom/post
fi

export SENDCOM=${SENDCOM:-YES}
export SCRUBDATA=${SCRUBDATA:-YES}

if [ "${SCRUBDATA}" = YES ]; then
  rm -rf $DATA
fi
mkdir -p ${COMOUTpost}
mkdir -p ${intercom}
mkdir -p $DATA
cd $DATA

# Execute ex-script
${HOMEhafs}/scripts/exhafs_atm_post.sh

export KEEPDATA=${KEEPDATA:-YES}
if [ "${KEEPDATA^^}" != YES ]; then
  rm -rf $DATA
fi

date
