#!/bin/sh

set -xe

date
source ${USHhafs}/hafs_pre_job.sh.inc
HOLDVARS=${HOLDVARS:-/can/not/find/storm1.holdvars.txt}
source ${HOLDVARS}

export EXPT=${EXPT:-HAFS}
export SUBEXPT=${SUBEXPT:-${EXPT}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:-00}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}

export NHRS=${NHRS:-126}
export ENSDA=${ENSDA:-NO}
if [ ${ENSDA} = YES ]; then
  export NBDYHRS=${NBDYHRS_ENS:-3}
  export CASE=${CASE_ENS:-C768}
  export CRES=`echo $CASE | cut -c 2-`
  export gtype=${gtype_ens:-regional}           # grid type = uniform, str
  export ictype=${ictype_ens:-gfsnemsio} # gfsnemsio
  export bctype=${bctype_ens:-gfsnemsio} # gfsnemsio, gfsgrib2_master, gfsgrib2_0p25, gfsgrib2_0p50, gfsgrib2_1p00
  export LEVS=${LEVS_ENS:-65}
else
  export NBDYHRS=${NBDYHRS:-3}
  export CASE=${CASE:-C768}
  export CRES=`echo $CASE | cut -c 2-`
  export gtype=${gtype:-regional}           # grid type = uniform, stretch, nest, or stand alone regional
  export ictype=${ictype:-gfsnemsio} # gfsnemsio
  export bctype=${bctype:-gfsnemsio} # gfsnemsio, gfsgrib2_master, gfsgrib2_0p25, gfsgrib2_0p50, gfsgrib2_1p00
  export LEVS=${LEVS:-65}
fi
export NTRAC=7            # output all gfdl mp tracers

####################################
# Specify Execution Areas
####################################
export HOMEhafs=${HOMEhafs:-/gpfs/hps3/emc/hwrf/noscrub/${USER}/save/HAFS}
export WORKhafs=${WORKhafs:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/${CDATE}/${STORMID}}
export COMIN=${COMIN:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMOUT=${COMOUT:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMhafs=${COMhafs:-${COMOUT}}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

export WGRIB2=${WGRIB2:-wgrib2}
export CHGRESCUBEEXEC=${EXEChafs}/hafs_chgres_cube.x

####################################
# Load Modules if Needed
####################################
export machine=${WHERE_AM_I:-wcoss_cray} # platforms: wcoss_cray, wcoss_dell_p3, hera, orion, jet
#export RUN_ENVIR=${RUN_ENVIR:-prod}
export RUN_ENVIR=${envir:-prod}
if [ "$RUN_ENVIR" = prod ]; then
  #module use ${HOMEhafs}/modulefiles
  #module load modulefile.hafs.run.${machine}
  if [ "$machine" = wcoss_dell_p3 ]; then
    module unload NetCDF
    module unload HDF5-serial
  fi
  #source ${HOMEhafs}/sorc/hafs_utils.fd/modulefiles/build.${machine}
  module use ${HOMEhafs}/sorc/hafs_utils.fd/modulefiles
  module load build.${machine}.intel
  module list
fi

#####################################
# Set up job node/core/run environment variables
#####################################
source ${USHhafs}/hafs_runcmd.sh.inc

####################################
# Run setpdy and initialize PDY variables
####################################
#setpdy.sh
#. ./PDY

PDYtmp=$(echo ${YMDH} | cut -c 1-8 )
export PDY=${PDY:-${PDYtmp}}

if [ ${ENSDA} = YES ]; then
  NDATE=${NDATE:-ndate}
  CDATEprior=`${NDATE} -6 $CDATE`
  export PDY_prior=`echo ${CDATEprior} | cut -c1-8`
  export cyc_prior=`echo ${CDATEprior} | cut -c9-10`
fi

#####################################
# Working directories
#####################################
if [ ${ENSDA} = YES ]; then
  export ENSID=$( printf "%03d" "${ENSID:-001}" )
  export OUTDIR=${OUTDIR:-${WORKhafs}/intercom/chgres_ens/mem${ENSID}}
  export DATA=${WORKhafs}/chgres_ic_ens/mem${ENSID}
else
  export OUTDIR=${OUTDIR:-${WORKhafs}/intercom/chgres}
  export DATA=${WORKhafs}/chgres_ic
fi

export SCRUBDATA=${SCRUBDATA:-YES}

if [ "${SCRUBDATA}" = YES ]; then
  rm -rf $DATA
fi

mkdir -p $OUTDIR $DATA
cd $DATA

#####################################
# Define COM directories
#####################################
#export COMROOT=${COMROOT:-/gpfs/hps/nco/ops/com}
#export COMgfs=${COMgfs:-/${COMROOT}/gfs/prod}
export COMgfs=${COMgfs:-/gpfs/dell1/nco/ops/com/gfs/para}

if [ $GFSVER = "PROD2021" ]; then
 if [ ${ENSDA} = YES ]; then
  export INIDIR=${COMgfs}/enkfgdas.${PDY_prior}/${cyc_prior}/atmos/mem${ENSID}
 else
  export INIDIR=${COMgfs}/gfs.$PDY/$cyc/atmos
 fi
elif [ $GFSVER = "PROD2019" ]; then
 if [ ${ENSDA} = YES ]; then
  export INIDIR=${COMgfs}/enkfgdas.${PDY_prior}/${cyc_prior}/mem${ENSID}
 else
  export INIDIR=${COMgfs}/gfs.$PDY/$cyc
 fi
else
  export INIDIR=${COMgfs}/gfs.$PDY/$cyc
fi

#####################################
# Generate the ICs and BC hour 0
#####################################
if [ $gtype = regional ] ; then
  export REGIONAL=1
  export HALO=4
else
#
# for gtype = uniform, stretch, or nest
#
  export REGIONAL=0
fi

#####################################
# Execute the script.
${HOMEhafs}/scripts/exhafs_chgres_ic.sh
export err=$?
#####################################

exit $err
