#!/bin/sh

set -xe

date
source ${USHhafs}/hafs_pre_job.sh.inc
HOLDVARS=${HOLDVARS:-/can/not/find/storm1.holdvars.txt}
source ${HOLDVARS}

export EXPT=${EXPT:-HAFS}
export SUBEXPT=${SUBEXPT:-${EXPT}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:-00}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}

export ENSDA=${ENSDA:-NO}
if [ "${ENSDA}" = YES ]; then
  export NHRS=${NHRS_ENS:-126}
  export NBDYHRS=${NBDYHRS_ENS:-3}
  export NOUTHRS=${NOUTHRS_ENS:-3}
  export CASE=${CASE_ENS:-C768}
  export CRES=`echo $CASE | cut -c 2-`
  export gtype=${gtype_ens:-regional}           # grid type = uniform, stretch, nest, or regional
  export LEVS=${LEVS_ENS:-65}
else
  export NHRS=${NHRS:-126}
  export NBDYHRS=${NBDYHRS:-3}
  export NOUTHRS=${NOUTHRS:-3}
  export CASE=${CASE:-C768}
  export CRES=`echo $CASE | cut -c 2-`
  export gtype=${gtype:-regional}           # grid type = uniform, stretch, nest, or regional
  export LEVS=${LEVS:-65}
fi
export NTRAC=7            # output all gfdl mp tracers

####################################
# Specify Execution Areas
####################################
export HOMEhafs=${HOMEhafs:-/gpfs/hps3/emc/hwrf/noscrub/${USER}/save/HAFS}
export WORKhafs=${WORKhafs:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/${CDATE}/${STORMID}}
export COMIN=${COMIN:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMOUT=${COMOUT:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMhafs=${COMhafs:-${COMOUT}}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

export FIXam=${FIXhafs}/fix_am
export FIXfv3=${FIXhafs}/fix_fv3

export FIXnew=${FIXhafs}/fix
export CO2DIR=${FIXam}/fix_co2_proj

export GSIEXEC=${EXEChafs}/hafs_gsi.x
export ENKFEXEC=${EXEChafs}/hafs_enkf.x

export MPISERIAL=${MPISERIAL:-${EXEChafs}/hafs_mpiserial.x}
export NDATE=${NDATE:-/gpfs/hps/nco/ops/nwprod/prod_util.v1.0.32/exec/ndate}

####################################
# Load Modules if Needed
####################################
export machine=${WHERE_AM_I:-wcoss_cray} # platforms: wcoss_cray, wcoss_dell_p3, hera, orion, jet
#export RUN_ENVIR=${RUN_ENVIR:-prod}
export RUN_ENVIR=${envir:-prod}
if [ "$RUN_ENVIR" = prod ]; then
  module use ${HOMEhafs}/modulefiles
  module load modulefile.hafs.run.${machine}
  module use $HOMEhafs/sorc/hafs_gsi.fd/modulefiles
  #module load modulefile.ProdGSI.${machine}
  source $HOMEhafs/sorc/hafs_gsi.fd/modulefiles/modulefile.ProdGSI.${machine}
  #env
  module list
fi

#####################################
# Set up job node/core/run environment variables
#####################################
source ${USHhafs}/hafs_runcmd.sh.inc

####################################
# Run setpdy and initialize PDY variables
####################################
#setpdy.sh
#. ./PDY

PDYtmp=$(echo ${YMDH} | cut -c 1-8 )
export PDY=${PDY:-${PDYtmp}}

#####################################
# Working directories
#####################################
if [ ${HX_ENS:-NO} = YES ]; then
  export ENSID=${ENSID:-001}
  export MEMSTR="mem${ENSID}"
else
  export ENSID="mean"
  export MEMSTR="ensmean"
fi

export DATA=${WORKhafs}/enkf_hx/${MEMSTR}
export SCRUBDATA=${SCRUBDATA:-YES}

if [ "${SCRUBDATA}" = YES ]; then
  rm -rf $DATA
fi

mkdir -p $DATA
cd $DATA

#####################################
# Execute the script.
${HOMEhafs}/scripts/exhafs_enkf_hx.sh
export err=$?
#####################################

exit $err
