#!/bin/sh

date
export PS4='+ $SECONDS + '
set -xue

export HOMEhafs=${HOMEhafs:?}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

source ${USHhafs}/hafs_pre_job.sh.inc
source ${HOLDVARS:-storm1.holdvars.txt}
source ${USHhafs}/hafs_runcmd.sh.inc

export machine=${WHERE_AM_I:-wcoss_cray}
export envir=${envir:-prod} # prod, para, test
export RUN_ENVIR=${RUN_ENVIR:-dev} # nco or dev
if [ "$RUN_ENVIR" != nco ]; then
  module use ${HOMEhafs}/sorc/hafs_forecast.fd/modulefiles/${machine}
  module load fv3
  module list
  env
fi

# Run setpdy and initialize PDY variables
#setpdy.sh
#. ./PDY
export PDY=${PDY:-$(echo ${YMDH} | cut -c 1-8 )}

export WORKhafs=${WORKhafs:?}
export COMIN=${COMIN:?}
export COMOUT=${COMOUT:?}
export COMhafs=${COMhafs:-${COMOUT}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:?}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}
export ENSDA=${ENSDA:-NO}

if [ "${ENSDA}" = YES ]; then
  export ENSID=${ENSID:-001}
  export FIXgrid=${FIXgrid:-${WORKhafs}/intercom/grid_ens}
  export INPdir=${INPdir:-${WORKhafs}/intercom/chgres_ens/mem${ENSID}}
  export DATA=${WORKhafs}/forecast_ens/mem${ENSID}
else
  export FIXgrid=${FIXgrid:-${WORKhafs}/intercom/grid}
  export INPdir=${INPdir:-${WORKhafs}/intercom/chgres}
  export DATA=${WORKhafs}/forecast
fi

export SCRUBDATA=${SCRUBDATA:-YES}
if [ "${SCRUBDATA}" = YES ]; then
  rm -rf $DATA
fi

mkdir -p $DATA
cd $DATA

# Execute the exscript
${HOMEhafs}/scripts/exhafs_forecast.sh
export err=$?
exit $err

export KEEPDATA=${KEEPDATA:-YES}
if [ "${KEEPDATA^^}" != YES ]; then
  rm -rf $DATA
fi

date
