#!/bin/sh

set -xe

HOLDVARS=${HOLDVARS:-/can/not/find/storm1.holdvars.txt}
source ${HOLDVARS}

export EXPT=${EXPT:-HAFS}
export SUBEXPT=${SUBEXPT:-${EXPT}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:-00}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}

export NHRS=${NHRS:-126}
export NBDYHRS=${NBDYHRS:-3}
export CASE=${CASE:-C768}
export CRES=`echo $CASE | cut -c 2-`
export gtype=${GTYPE:-regional}           # grid type = uniform, stretch, nest, or stand alone regional
export ictype=${ICTYPE:-pfv3gfs}
export LEVS=${LEVELS:-65}
export NTRAC=7			# output all gfdl mp tracers

####################################
# Specify Execution Areas
####################################
export HOMEhafs=${HOMEhafs:-/gpfs/hps3/emc/hwrf/noscrub/${USER}/save/HAFS}
export WORKhafs=${WORKhafs:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/${CDATE}/${STORMID}}
export COMIN=${COMIN:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMOUT=${COMOUT:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMhafs=${COMhafs:-${COMOUT}}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

export HOMEgfs=${HOMEgfs:-/gpfs/hps3/emc/hwrf/noscrub/${USER}/save/HAFS/fv3gfs}
export EXECgfs=${EXECgfs:-${HOMEgfs}/exec}
export FIXgfs=${FIXgfs:-${HOMEgfs}/fix}
export USHgfs=${USHfv3:-${HOMEgfs}/ush}

export FIXam=${FIXhafs}/fix_am
export FIXfv3=${FIXhafs}/fix_fv3
#If static domain
#export FIXfv3=${FIXhafs}/fix_fv3_regional_static
#export FIXfv3=${FIXhafs}/fix_fv3_globnest_static
#else relocatable domain
#export FIXfv3=${WORKhafs}/grid

export CHGRESEXEC=${EXEChafs}/hafs_chgres.x
export CHGRESSH=${USHhafs}/hafs_chgres.sh

####################################
# Load Modules if Needed
####################################
export machine=${WHERE_AM_I:-wcoss_cray} # platforms: wcoss_cray, wcoss_dell_p3, theia, jet
#export RUN_ENVIR=${RUN_ENVIR:-prod}
export RUN_ENVIR=${envir:-prod}
if [ "$RUN_ENVIR" = prod ]; then
  module use ${HOMEhafs}/modulefiles
  module load modulefile.hafs.run.${machine}
  module list
fi

#####################################
# Environment settings
#####################################
  export TOTAL_TASKS=${TOTAL_TASKS:-1}
  export NCTSK=${NCTSK:-1}
  export NCNODE=${NCNODE:-24}
  export OMP_NUM_THREADS=${OMP_NUM_THREADS:-24}
  export OMP_NUM_THREADS_CH=${OMP_NUM_THREADS:-24}
  export KMP_STACKSIZE=1024m
if [ "$machine" = wcoss_cray ]; then
  #export NODES=1
  export APRUNS=${APRUNS:-"aprun -b -j1 -n1 -N1 -d1 -cc depth"}
  export APRUNF=${APRUNF:-"aprun -b -j1 -n${TOTAL_TASKS} -N${NCTSK} -d${OMP_NUM_THREADS} -cc depth cfp"}
  export APRUNC=${APRUNC:-"aprun -b -j1 -n${TOTAL_TASKS} -N${NCTSK} -d${OMP_NUM_THREADS} -cc depth"}
  export KMP_AFFINITY=disabled
elif [ "$machine" = wcoss_dell_p3 ]; then
  export APRUNS=${APRUNS:-"time"}
  export APRUNF=${APRUNF:-"mpirun cfp"}
  export APRUNC=${APRUNC:-"mpirun"}
elif [ "$machine" = theia ]; then
  export APRUNS=${APRUNS:-"time"}
  export APRUNF=${APRUNF:-"srun --multi-prog"}
  export APRUNC=${APRUNC:-"srun"}
elif [ "$machine" = jet ]; then
  export APRUNS=${APRUNS:-"time"}
  export APRUNF=${APRUNF:-"srun --multi-prog"}
  export APRUNC=${APRUNC:-"srun"}
else
  export APRUNS=${APRUNS:-"time"}
  export APRUNF=${APRUNF:-${MPISERIAL:-mpiserial}}
  export APRUNC=${APRUNC:-"mpirun"}
fi

env

####################################
# Run setpdy and initialize PDY variables
####################################
#setpdy.sh
#. ./PDY

PDYtmp=$(echo ${YMDH} | cut -c 1-8 )
export PDY=${PDY:-${PDYtmp}}

#####################################
# Working directories
#####################################
export INPdir=${INPdir:-${WORKhafs}/intercom/chgres}
export OUTDIR=${OUTDIR:-${WORKhafs}/chgres_bc/out}
export DATA=${WORKhafs}/chgres_bc/work

export SCRUBDATA=${SCRUBDATA:-YES}

if [ "${SCRUBDATA}" = YES ]; then
  rm -rf $DATA $OUTDIR 
fi

mkdir -p $INPdir $OUTDIR $DATA
cd $DATA

#####################################
# Define COM directories
#####################################
#export COMROOT=${COMROOT:-/gpfs/hps/nco/ops/com}
#export COMgfs=${COMgfs:-/${COMROOT}/gfs/prod}
export COMgfs=${COMgfs:-/gpfs/dell1/nco/ops/com/gfs/para}
export INIDIR=${COMgfs}/gfs.$PDY/$cyc

#####################################
# Generate the BCs
#####################################
export REGIONAL=2

NBDYHRS=${NBDYHRS:-3}
hour=${NBDYHRS:-3}
end_hour=$NHRS
while (test "$hour" -le "$end_hour")
  do
  if [ $hour -lt 10 ]; then
    hour_name='00'$hour
  elif [ $hour -lt 100 ]; then
    hour_name='0'$hour
  else
    hour_name=$hour
  fi
#
# create input file for cfp in order to run multiple copies of chgres.sh simultaneously
# since we are going to run simultaneously, we want different working directories for each hour
#
  BC_DATA=${DATA}/bctmp_$hour_name
  rm -rf $BC_DATA
  mkdir -p $BC_DATA
  echo "env REGIONAL=2 HALO=4 bchour=$hour_name DATA=$BC_DATA ${HOMEhafs}/scripts/exhafs_chgres.sh >&out.chgres.$hour_name" >> bcfile.input
  hour=`expr $hour + ${NBDYHRS}`
done

################################
# Execute the script.
################################
  
if [ $machine = wcoss_cray ]; then
  export APRUNC="time"
  export OMP_NUM_THREADS_CH=${OMP_NUM_THREADS:-24}
  aprun -j 1 -n ${TOTAL_TASKS} -N 1 -d ${OMP_NUM_THREADS_CH} -cc depth cfp bcfile.input
  rm -f bcfile.input
elif [ $machine = wcoss_dell_p3 ]; then
  #export OMP_NUM_THREADS=24
  export OMP_NUM_THREADS_CH=${OMP_NUM_THREADS:-24}
  mpirun cfp bcfile.input
  rm -f bcfile.input
elif [ "$machine" = theia ]; then
  export APRUNC="time"
  export OMP_NUM_THREADS_CH=${OMP_NUM_THREADS:-24}
  # to be implemented by srun --multi-prog
  #srun --multi-prog 
  echo "ERROR: To be implemented by using srun --multi-prog"
  echo "ERROR: Exitting"
  exit 1
elif [ "$machine" = jet ]; then
  export APRUNC="time"
  export OMP_NUM_THREADS_CH=${OMP_NUM_THREADS:-24}
  # to be implemented by srun --multi-prog
  #srun --multi-prog 
  echo "ERROR: To be implemented by using srun --multi-prog"
  echo "ERROR: Exitting"
  exit 1
else
  echo "ERROR: Unknow machine, currently not supportted"
  echo "ERROR: Exitting"
  exit 1
fi

mv $OUTDIR/gfs_bndy*nc $INPdir/.

exit $err
