#!/bin/sh

date
export PS4='+ $SECONDS + '
set -x

export cycle=${cycle:-t${cyc:?}z}
export storm_num=${storm_num:-1}
export stormlabel=${stormlabel:-storm$storm_num}
export hafs_ver=${hafs_ver:?}
export NET=${NET:?}
export RUN=${RUN:?}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}
export EMAIL_SDM=${EMAIL_SDM:-NO}
export SCRUBDATA=${SCRUBDATA:-YES}
# HAFS workflow jobs use shared working dir, and the CLEANUP or SCRUB job will clean up WORKhafs
#export KEEPDATA=${KEEPDATA:-YES}
export KEEPDATA=YES

export HOMEhafs=${HOMEhafs:-${OPSROOT:?}/hafs.${hafs_ver:?}}
export USHhafs=$HOMEhafs/ush
export EXEChafs=$HOMEhafs/exec
export PARMhafs=$HOMEhafs/parm
export FIXhafs=$HOMEhafs/fix

export WORKhafs=${WORKhafs:-${DATAROOT:?}/${RUN:?}${storm_num:?}_${cyc:?}_${envir:?}_${hafs_ver:?}}

source ${USHhafs}/hafs_pre_job.sh.inc
export machine=${WHERE_AM_I:-wcoss2}
if [[ ${machine}  = "wcoss2" ]]; then
  module reset
  module load PrgEnv-intel/${PrgEnv_intel_ver}
  module load craype/${craype_ver}
  module load intel/${intel_ver}
  module load cray-mpich/${cray_mpich_ver}
  module load cray-pals/${cray_pals_ver}
  module load hdf5-A/${hdf5_ver}
  module load netcdf-A/${netcdf_ver}
  module load ve/hafs/${ve_hafs_ver}
  module load crtm/${crtm_ver}
  module load ncio-A/${ncio_ver}
  module load ncdiag-A/${ncdiag_ver}
  module load cfp/${cfp_ver}
  module load prod_util/${prod_util_ver}
fi
if [[ ${machine}  = "jet" ]] || [[ ${machine}  = "orion" ]] || [[ ${machine}  = "hercules" ]] || [[ ${machine}  = "hera" ]] || [[ ${machine}  = "ursa" ]]; then
  module purge
fi
if [[ ${machine}  = "gaeac6" ]]; then
  module reset
fi
ulimit -s unlimited
ulimit -a
module use $HOMEhafs/sorc/hafs_jedi.fd/modulefiles
module load HDAS/${machine}.intel
if [[ ${machine}  = "ursa" ]] || [[ ${machine}  = "jet" ]]; then
  module load intel-oneapi-mkl/2024.2.1
fi
export PYTHONPATH="${PYTHONPATH}:$HOMEhafs/sorc/hafs_jedi.fd/sorc/jcb/src/:$HOMEhafs/sorc/hafs_jedi.fd/sorc/hafs_jedi.fd/build/lib/python3.*"
export SALLOC_ACCOUNT=$SLURM_JOB_ACCOUNT
export SBATCH_ACCOUNT=$SLURM_JOB_ACCOUNT
export IODA_PRINT_RUNSTATS=1
export OMP_NUM_THREADS=1
export OMP_PROC_BIND=true
export I_MPI_COLL_INTRANODE=pt2pt

if [ -e $HOMEhafs/sorc/hafs_jedi.fd/build/lib/python3.10 ]; then
  export PYTHONPATH=$HOMEhafs/sorc/hafs_jedi.fd/build/lib/python3.10:${PYTHONPATH}
  export PYTHONPATH=${PYTHONPATH}:$HOMEhafs/sorc/hafs_jedi.fd/build/lib/python3.10/site-packages
  export PYTHONPATH=${PYTHONPATH}:${USHhafs}
elif [ -e $HOMEhafs/sorc/hafs_jedi.fd/build/lib/python3.11 ]; then
  export PYTHONPATH=$HOMEhafs/sorc/hafs_jedi.fd/build/lib/python3.11:${PYTHONPATH}
  export PYTHONPATH=${PYTHONPATH}:$HOMEhafs/sorc/hafs_jedi.fd/build/lib/python3.11/site-packages
  export PYTHONPATH=${PYTHONPATH}:${USHhafs}
else
  export PYTHONPATH=$HOMEhafs/sorc/hafs_jedi.fd/build/lib/python3.7:${PYTHONPATH}
  export PYTHONPATH=${PYTHONPATH}:$HOMEhafs/sorc/hafs_jedi.fd/build/lib/python3.7/site-packages
  export PYTHONPATH=${PYTHONPATH}:${USHhafs}
fi

source ${USHhafs}/hafs_runcmd.sh.inc

env

export COMhafs=${COMhafs:-$(compath.py ${envir}/${NET}/${hafs_ver})/${RUN}.${PDY}/${cyc}}
export CONFhafs=$COMhafs/$stormlabel.conf
export HOLDVARS=${HOLDVARS:-$COMhafs/$stormlabel.holdvars.txt}

source ${HOLDVARS}

export ANALYSIS_D01=${ANALYSIS_D01:-NO}
export ANALYSIS_D02=${ANALYSIS_D02:-NO}
export ENSDA=${ENSDA:-NO}

export CDATE=${CDATE:-${YMDH}}
yr=$(echo $CDATE | cut -c1-4)
mn=$(echo $CDATE | cut -c5-6)
dy=$(echo $CDATE | cut -c7-8)

export RESTARTout_dir=${WORKhafs}/intercom/ENS_PREP/mem${ENSID:-001}
export DATA=${WORKhafs}/ENS_PREP/mem${ENSID:-001}${jobidstr}

if [ "${SCRUBDATA:-YES}" = YES ]; then
  rm -rf $DATA
fi
mkdir -p $DATA
mkdir -p ${RESTARTout_dir}
cd $DATA

# Execute ex-script
${HOMEhafs}/scripts/exhafs_atm_ens_prep.sh
export err=$?; err_chk

# Cleanup DATA dir
cd ${WORKhafs}
if [ "${KEEPDATA:-YES}" != "YES" ]; then
  rm -rf $DATA
fi
date
