#!/bin/sh

date
export PS4='+ $SECONDS + '
set -x

export cycle=${cycle:-t${cyc:?}z}
export storm_num=${storm_num:-1}
export stormlabel=${stormlabel:-storm$storm_num}
export hafs_ver=${hafs_ver:?}
export NET=${NET:?}
export RUN=${RUN:?}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}
export EMAIL_SDM=${EMAIL_SDM:-NO}
export SCRUBDATA=${SCRUBDATA:-YES}
# HAFS workflow jobs use shared working dir, and the CLEANUP or SCRUB job will clean up WORKhafs
#export KEEPDATA=${KEEPDATA:-YES}
export KEEPDATA=YES

export HOMEhafs=${HOMEhafs:-${OPSROOT:?}/hafs.${hafs_ver:?}}
export USHhafs=$HOMEhafs/ush
export EXEChafs=$HOMEhafs/exec
export PARMhafs=$HOMEhafs/parm
export FIXhafs=$HOMEhafs/fix

export WORKhafs=${WORKhafs:-${DATAROOT:?}/${RUN:?}${storm_num:?}_${cyc:?}_${envir:?}_${hafs_ver:?}}

if [ "${RUN_ENVIR^^}" != "NCO" ]; then
  # Detect platform and load modules if not run by NCO
  source ${USHhafs}/hafs_pre_job.sh.inc
  export machine=${WHERE_AM_I:-wcoss2}
  module list
else
  # Run by NCO on WCOSS2
  export machine=${WHERE_AM_I:-wcoss2}
  # Prepend $USHhafs to python package search path
  export PYTHONPATH=$USHhafs${PYTHONPATH:+:$PYTHONPATH}
  # Initialize PDY
# setpdy.sh # only needed for the launch job
  # Get PDY
  source ${WORKhafs}/PDY
fi

source ${USHhafs}/hafs_runcmd.sh.inc

env

export COMhafs=${COMhafs:-$(compath.py ${envir}/${NET}/${hafs_ver})/${RUN}.${PDY}/${cyc}}
export CONFhafs=$COMhafs/$stormlabel.conf
export HOLDVARS=${HOLDVARS:-$COMhafs/$stormlabel.holdvars.txt}

source ${HOLDVARS}

export MERGE_TYPE=${MERGE_TYPE:-analysis}
export ENSDA=${ENSDA:-NO}
export ENSID=${ENSID:-000}
export FGAT_MODEL=${FGAT_MODEL:-gfs}
export FGAT_HR=${FGAT_HR:-00}

# Add multistorm env vars
export RUN_MULTISTORM=${RUN_MULTISTORM:-NO}
export FAKEWORKhafs=${FAKEWORKhafs:-$(echo "${WORKhafs/${STORMID}/${FAKESTORMID}}")}

################################################
export FGAT_MODEL=${FGAT_MODEL:-gfs}
export FGAT_HR=${FGAT_HR:-00}

run_needed=NO
if [ -d ${WORKhafs}/intercom/atm_merge_prep ]; then
  echo 'outside parent domain'
  run_needed=YES
  export run_needed=YES
fi

if [[ "${run_needed}" = "YES" ]] && [[ ${MERGE_TYPE} = init ]] ; then

  # Merge analysis or init
  if [ ${MERGE_TYPE} = analysis ]; then
    if [ "${ENSDA}" = YES ]; then
      export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
    else
      export DATA=${WORKhafs}/analysis_merge${jobidstr}
    fi
  elif [ ${MERGE_TYPE} = init ]; then
    if [ ${FGAT_MODEL} = gdas ]; then
      export DATA=${WORKhafs}/atm_merge_fgat${FGAT_HR}${jobidstr}
    else
      export DATA=${WORKhafs}/atm_merge${jobidstr}
    fi
  else
    echo "FATAL ERROR: unsupported MERGE_TYPE: ${MERGE_TYPE}"
    exit 1
  fi
  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
    rm -rf $DATA
  fi
  mkdir -p $DATA
  cd $DATA

  # Execute ex-script
  ${HOMEhafs}/scripts/exhafs_merge_test.sh
  export err=$?; err_chk

  # Cleanup DATA dir
  cd ${WORKhafs}
  if [ "${KEEPDATA:-YES}" != "YES" ]; then
    rm -rf $DATA
  fi

else

  # Merge analysis or init
  if [ ${MERGE_TYPE} = analysis ]; then
    if [ "${ENSDA}" = YES ]; then
      export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
    else
      export DATA=${WORKhafs}/analysis_merge${jobidstr}
    fi
  elif [ ${MERGE_TYPE} = init ]; then
    if [ "${ENSDA}" = YES ]; then
      export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
    else
      if [ ${FGAT_MODEL} = gdas ]; then
        export DATA=${WORKhafs}/atm_merge_fgat${FGAT_HR}${jobidstr}
      else
        export DATA=${WORKhafs}/atm_merge${jobidstr}
      fi
    fi
  else
    echo "FATAL ERROR: unsupported MERGE_TYPE: ${MERGE_TYPE}"
    exit 1
  fi
  
  if [ "${ANALYSIS_MODEL}" = "JEDI" ] || [ "${ANALYSIS_MODEL}" = "jedi" ]; then
   if [ ${ENSDA} = "YES" ] && [ ! -e "${COMOLD}" ] && [ ${MERGE_TYPE} = init ] ; then
     echo "RUN_ENSDA YES for JEDI will skip ens merge for the first cycle"
     echo "Do nothing. Exiting"
     exit
   fi
  fi
  
  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
    rm -rf $DATA
  fi
  mkdir -p $DATA
  cd $DATA
  
  # Execute ex-script
  ${HOMEhafs}/scripts/exhafs_merge.sh
  export err=$?; err_chk
  
  # Cleanup DATA dir
  cd ${WORKhafs}
  if [ "${KEEPDATA:-YES}" != "YES" ]; then
    rm -rf $DATA
  fi

fi
date
