#!/bin/sh

date
export PS4='+ $SECONDS + '
set -xue

export cycle=${cycle:-t${cyc:?}z}
export storm_num=${storm_num:-1}
export stormlabel=${stormlabel:-storm$storm_num}
export hafs_ver=${hafs_ver:-v1.0.0}
export NET=${NET:-hafs}
export RUN=${RUN:-hfsa}
export RUN_ENVIR=${RUN_ENVIR:-NCO}

export SENDDBN=${SENDDBN:-NO}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}
export SENDECF=${SENDECF:-NO}
export EMAIL_SDM=${EMAIL_SDM:-NO}
export SCRUBDATA=${SCRUBDATA:-YES}
export KEEPDATA=${KEEPDATA:-YES}

export HOMEhafs=${HOMEhafs:-${OPSROOT:?}/hafs.${hafs_ver:?}}
export USHhafs=$HOMEhafs/ush
export EXEChafs=$HOMEhafs/exec
export PARMhafs=$HOMEhafs/parm
export FIXhafs=$HOMEhafs/fix

export WORKhafs=${WORKhafs:-${DATAROOT:?}/${RUN:?}${storm_num:?}_${cyc:?}_${envir:?}}

if [ "${RUN_ENVIR^^}" != "NCO" ]; then
  # Detect platform and load modules if not run by NCO
  source ${USHhafs}/hafs_pre_job.sh.inc
  export machine=${WHERE_AM_I:-wcoss2}
  module use $HOMEhafs/sorc/hafs_gsi.fd/modulefiles
  if [ ${machine}  = "hera" ]; then
    module load gsi_${machine}.intel
  else
    module load gsi_${machine}
  fi
  module list
else
  # Run by NCO on WCOSS2
  export machine=${WHERE_AM_I:-wcoss2}
  # Prepend $USHhafs to python package search path
  export PYTHONPATH=$USHhafs${PYTHONPATH:+:$PYTHONPATH}
  # Initialize PDY
# setpdy.sh # only needed for the launch job
  # Get PDY
  source ${WORKhafs}/PDY
fi

source ${USHhafs}/hafs_runcmd.sh.inc

env

export COMhafs=${COMhafs:-$(compath.py ${envir}/${NET}/${hafs_ver})/${RUN}.${PDY}/${cyc}}
export CONFhafs=$COMhafs/$stormlabel.conf
export HOLDVARS=${HOLDVARS:-$COMhafs/$stormlabel.holdvars.txt}

source ${HOLDVARS}

export ENSDA=${ENSDA:-NO}
export ldo_enscalc_option=${ldo_enscalc_option:?} # 0, enkf_update; 1, enkf_mean; 2, enkf_recenter

if [ ${ldo_enscalc_option} -eq 0 ]; then
  export DATA=${WORKhafs}/enkf_update
elif [ ${ldo_enscalc_option} -eq 1 ]; then
  export DATA=${WORKhafs}/enkf_mean
elif [ ${ldo_enscalc_option} -eq 2 ]; then
  export DATA=${WORKhafs}/enkf_recenter
else
  echo "FATAL ERROR: wrong ldo_enscalc_option of ${ldo_enscalc_option}"
  exit 1
if

if [ "${SCRUBDATA:-YES}" = YES ]; then
  rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA

# Execute ex-script
${HOMEhafs}/scripts/exhafs_enkf.sh
status=$?; [[ $status -ne 0 ]] && exit $status

# Cleanup DATA dir
cd ${WORKhafs}
if [ "${KEEPDATA:-YES}" != YES ]; then
  rm -rf $DATA
fi

date
