#!/bin/sh

set -xe

date
source ${USHhafs}/hafs_pre_job.sh.inc
HOLDVARS=${HOLDVARS:-/can/not/find/storm1.holdvars.txt}
source ${HOLDVARS}

export EXPT=${EXPT:-HAFS}
export SUBEXPT=${SUBEXPT:-${EXPT}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:-00}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}

export ENSDA=${ENSDA:-NO}
if [ ${ENSDA} = YES ]; then
  export NHRS=${NHRS_ENS:-126}
  export NBDYHRS=${NBDYHRS_ENS:-3}
  export NOUTHRS=${NOUTHRS_ENS:-3}
  export CASE=${CASE_ENS:-C768}
  export CRES=`echo $CASE | cut -c 2-`
  export gtype=${gtype_ens:-regional}           # grid type = uniform, stretch, nest, or regional
  export LEVS=${LEVS_ENS:-65}
else
  export NHRS=${NHRS:-126}
  export NBDYHRS=${NBDYHRS:-3}
  export NOUTHRS=${NOUTHRS:-3}
  export CASE=${CASE:-C768}
  export CRES=`echo $CASE | cut -c 2-`
  export gtype=${gtype:-regional}           # grid type = uniform, stretch, nest, or regional
  export LEVS=${LEVS:-65}
fi
export NTRAC=7            # output all gfdl mp tracers

export output_grid=${output_grid:-rotated_latlon}
export synop_gridspecs=${synop_gridspecs:-"latlon 246.6:4112:0.025 -2.4:1976:0.025"}
export trker_gridspecs=${trker_gridspecs:-"latlon 246.6:4112:0.025 -2.4:1976:0.025"}
export out_prefix=${out_prefix:-$(echo "${STORM}${STORMID}.${YMDH}" | tr '[A-Z]' '[a-z]')}

####################################
# Specify Execution Areas
####################################
export HOMEhafs=${HOMEhafs:-/gpfs/hps3/emc/hwrf/noscrub/${USER}/save/HAFS}
export WORKhafs=${WORKhafs:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/${CDATE}/${STORMID}}
export COMIN=${COMIN:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMOUT=${COMOUT:-/gpfs/hps3/ptmp/${USER}/${SUBEXPT}/com/${CDATE}/${STORMID}}
export COMhafs=${COMhafs:-${COMOUT}}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

export HOMEgfs=${HOMEgfs:-/gpfs/hps3/emc/hwrf/noscrub/${USER}/save/HAFS/fv3gfs}
export EXECgfs=${EXECgfs:-${HOMEgfs}/exec}
export FIXgfs=${FIXgfs:-${HOMEgfs}/fix}
export USHgfs=${USHfv3:-${HOMEgfs}/ush}

export POSTEXEC=${EXEChafs}/hafs_post.x

export MPISERIAL=${MPISERIAL:-${EXEChafs}/hafs_mpiserial.x}
export NDATE=${NDATE:-/gpfs/hps/nco/ops/nwprod/prod_util.v1.0.32/exec/ndate}
#export WGRIB2=${WGRIB2:-/gpfs/hps/nco/ops/nwprod/grib_util.v1.1.0/exec/wgrib2}
export WGRIB2=${WGRIB2:-/u/Wesley.Ebisuzaki/bin/wgrib2.v2.0.8b9}
#export WGRIB2=/u/Wesley.Ebisuzaki/bin/wgrib2.v2.0.8
#export WGRIB2=/u/Wesley.Ebisuzaki/bin/wgrib2.v2.0.8b9
export GRB2INDEX=${GRB2INDEX:-/gpfs/hps/nco/ops/nwprod/grib_util.v1.1.0/exec/grb2index}

####################################
# Load Modules if Needed
####################################
export machine=${WHERE_AM_I:-wcoss_cray} # platforms: wcoss_cray, wcoss_dell_p3, hera, orion, jet
#export RUN_ENVIR=${RUN_ENVIR:-prod}
export RUN_ENVIR=${envir:-prod}
if [ "$RUN_ENVIR" = prod ]; then
  #module purge
  #module use ${HOMEhafs}/modulefiles
  #module load modulefile.hafs.base.${machine}
  #module load modulefile.hafs.run.${machine}
  if [ "$machine" = wcoss_dell_p3 ]; then
    module unload NetCDF
    module unload HDF5-serial
  fi
  if [ "$machine" = wcoss_cray ]; then
    module unload zlib-intel-haswell/1.2.7
    module unload g2-intel/2.5.0
    module unload w3nco-intel/2.0.6
    module unload bacio-intel/2.0.1
    module unload sp-intel/2.0.2
    module unload w3emc-intel/2.2.0
    module unload nemsio-intel/2.2.2
  fi
  if [ "$machine" = orion ]; then
     module purge
     module use ${HOMEhafs}
     module load modulefiles/modulefile.hafs.base.run.${machine}
#    module unload nco netcdf hdf5
  fi
  if [ "$machine" = hera ]; then
     module purge
  fi
  module use ${HOMEhafs}/sorc/hafs_post.fd/modulefiles
  module load ${machine}
  module list
fi

#####################################
# Set up job node/core/run environment variables
#####################################
source ${USHhafs}/hafs_runcmd.sh.inc

####################################
# Run setpdy and initialize PDY variables
####################################
#setpdy.sh
#. ./PDY

PDYtmp=$(echo ${YMDH} | cut -c 1-8 )
export PDY=${PDY:-${PDYtmp}}

#####################################
# Working directories
#####################################
if [ ${ENSDA} = YES ]; then
  export ENSID=${ENSID:-001}
  export INPdir=${INPdir:-${WORKhafs}/forecast_ens/mem${ENSID}}
  export DATA=${WORKhafs}/post_ens/mem${ENSID}
  export COMOUTpost=${COMhafs}/post_ens/mem${ENSDA}
  export intercom=${WORKhafs}/intercom/post_ens/mem${ENSID}

else
  export INPdir=${INPdir:-${WORKhafs}/forecast}
  export DATA=${WORKhafs}/post
  export COMOUTpost=${COMhafs}
  export intercom=${WORKhafs}/intercom/post
fi

export SENDCOM=${SENDCOM:-YES}
export SCRUBDATA=${SCRUBDATA:-YES}

if [ "${SCRUBDATA}" = YES ]; then
  rm -rf $DATA
  rm -f $INPdir/postf???
  rm -rf ${intercom}
fi

mkdir -p ${COMOUTpost}
mkdir -p ${intercom}
mkdir -p $DATA
cd $DATA

#####################################
# Execute the script.
${HOMEhafs}/scripts/exhafs_post.sh
export err=$?
#####################################

exit $err
