#!/bin/sh

date
export PS4='+ $SECONDS + '
set -xue

export HOMEhafs=${HOMEhafs:?}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

source ${USHhafs}/hafs_pre_job.sh.inc
source ${HOLDVARS:-storm1.holdvars.txt}

export machine=${WHERE_AM_I:-wcoss_cray}
export envir=${envir:-prod} # prod, para, test
export RUN_ENVIR=${RUN_ENVIR:-dev} # nco or dev
if [ "${RUN_ENVIR^^}" != NCO ]; then
  if [ "${machine}" = "hera" ]; then
    module unload intelpython
  fi
  module use ${HOMEhafs}/sorc/hafs_forecast.fd/modulefiles
  module unload intelpython
  if [ "${machine}" = "wcoss_cray" ] || [ "${machine}" = "wcoss_dell_p3" ]; then
    module load ufs_${machine}
  else
    module load ufs_${machine}.intel
  fi
  module list
fi

source ${USHhafs}/hafs_runcmd.sh.inc

# Run setpdy and initialize PDY variables
#setpdy.sh
#. ./PDY
export PDY=${PDY:-$(echo ${YMDH} | cut -c 1-8 )}

export WORKhafs=${WORKhafs:?}
export COMIN=${COMIN:?}
export COMOUT=${COMOUT:?}
export COMhafs=${COMhafs:-${COMOUT}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:?}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}
export ENSDA=${ENSDA:-NO}

# KKUROSAWA
export LONG_FORECAST_ENS_FLAG=YES
export ENSID=${ENSID:-001}
export INPdir=${INPdir:-${WORKhafs}/intercom/chgres}  # <-- !!
export DATA=${WORKhafs}/long_forecast_ens/mem${ENSID} # <-- !!
export FIXgrid=${FIXgrid:-${WORKhafs}/intercom/grid_ens}

if [ $ENSID -le 10 ]; then
  export SCRUBDATA=${SCRUBDATA:-YES}
  if [ "${SCRUBDATA}" = YES ]; then
    rm -rf $DATA
  fi
  
  mkdir -p $DATA
  cd $DATA
  
  # Execute ex-script
  ${HOMEhafs}/scripts/exhafs_forecast.sh
  export err=$?
  exit $err
  
  export KEEPDATA=${KEEPDATA:-YES}
  if [ "${KEEPDATA^^}" != YES ]; then
    rm -rf $DATA
  fi
fi

date
