#!/bin/sh

date
export PS4='+ $SECONDS + '
set -xue

export cycle=${cycle:-t${cyc:?}z}
export storm_num=${storm_num:-1}
export stormlabel=${stormlabel:-storm$storm_num}
export hafs_ver=${hafs_ver:?}
export NET=${NET:?}
export RUN=${RUN:?}
export RUN_ENVIR=${RUN_ENVIR:?}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}
export EMAIL_SDM=${EMAIL_SDM:-NO}
export SCRUBDATA=${SCRUBDATA:-YES}
# HAFS workflow jobs use shared working dir, and the CLEANUP or SCRUB job will clean up WORKhafs
#export KEEPDATA=${KEEPDATA:-YES}
export KEEPDATA=YES

export HOMEhafs=${HOMEhafs:-${OPSROOT:?}/hafs.${hafs_ver:?}}
export USHhafs=$HOMEhafs/ush
export EXEChafs=$HOMEhafs/exec
export PARMhafs=$HOMEhafs/parm
export FIXhafs=$HOMEhafs/fix

export WORKhafs=${WORKhafs:-${DATAROOT:?}/${RUN:?}${storm_num:?}_${cyc:?}_${envir:?}_${hafs_ver:?}}

if [ "${RUN_ENVIR^^}" != "NCO" ]; then
  # Detect platform and load modules if not run by NCO
  source ${USHhafs}/hafs_pre_job.sh.inc
  export machine=${WHERE_AM_I:-wcoss2}
  module list
else
  # Run by NCO on WCOSS2
  export machine=${WHERE_AM_I:-wcoss2}
  # Prepend $USHhafs to python package search path
  export PYTHONPATH=$USHhafs${PYTHONPATH:+:$PYTHONPATH}
  # Initialize PDY
# setpdy.sh # only needed for the launch job
  # Get PDY
  source ${WORKhafs}/PDY
fi

source ${USHhafs}/hafs_runcmd.sh.inc

env

export COMhafs=${COMhafs:-$(compath.py ${envir}/${NET}/${hafs_ver})/${RUN}.${PDY}/${cyc}}
export CONFhafs=$COMhafs/$stormlabel.conf
export HOLDVARS=${HOLDVARS:-$COMhafs/$stormlabel.holdvars.txt}

source ${HOLDVARS}

export DATA=${WORKhafs}/ocn_prep

if [ "${SCRUBDATA:-YES}" = "YES" ]; then
  rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA

# Execute ex-script
if [[ "${run_docn:-no}" == yes ]] ; then
  ${HOMEhafs}/scripts/exhafs_docn_prep.sh
  status=$?; [[ $status -ne 0 ]] && exit $status
fi

if [[ "${run_ocean:-no}" == yes ]] && [[ "${ocean_model}" == hycom ]] ; then
  ${HOMEhafs}/scripts/exhafs_ocn_prep.py
  status=$?; [[ $status -ne 0 ]] && exit $status
fi

if [[ "${run_ocean:-no}" == yes ]] && [[ "${ocean_model}" == mom6 ]] ; then
  if [ "${machine}" != wcoos2 ] ; then
     module list
     module unload esmf
     module list
     if [ "${machine}" == orion ] ; then
        module use /work/noaa/hwrf/save/maristiz/modulefiles
        module load modulefile.OBC.run.orion
        export ESMFMKFILE=/work/noaa/hwrf/save/maristiz/miniconda3/envs/OBC_env/lib/esmf.mk
     fi
     if [ "${machine}" == hera ] ; then
        module use /scratch1/NCEPDEV/hwrf/save/Maria.Aristizabal/modulefiles/
        module load modulefile.OBC.run.hera
        export ESMFMKFILE=/scratch1/NCEPDEV/hwrf/save/Maria.Aristizabal/miniconda3/envs/OBC_env/lib/esmf.mk
     fi
     if [ "${machine}" == jet ] ; then
        module use /mnt/lfs4/HFIP/hwrfv3/Maria.Aristizabal/modulefiles
        module load modulefile.OBC.run.jet
        export ESMFMKFILE=/mnt/lfs4/HFIP/hwrfv3/Maria.Aristizabal/miniconda3/envs/OBC_env/lib/esmf.mk
     fi
  fi
  export PYTHONPATH=$PYTHONPATH:${HOMEhafs}/ush/mom6_obc
  ${HOMEhafs}/scripts/exhafs_ocn_prep.sh
  status=$?; [[ $status -ne 0 ]] && exit $status
fi

# Cleanup DATA dir
cd ${WORKhafs}
if [ "${KEEPDATA:-YES}" != "YES" ]; then
  rm -rf $DATA
fi

date
