#!/bin/sh

date
export PS4='+ $SECONDS + '
set -x

export cycle=${cycle:-t${cyc:?}z}
export storm_num=${storm_num:-1}
export stormlabel=${stormlabel:-storm$storm_num}
export hafs_ver=${hafs_ver:?}
export NET=${NET:?}
export RUN=${RUN:?}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}
export EMAIL_SDM=${EMAIL_SDM:-NO}
export SCRUBDATA=${SCRUBDATA:-YES}
# HAFS workflow jobs use shared working dir, and the CLEANUP or SCRUB job will clean up WORKhafs
#export KEEPDATA=${KEEPDATA:-YES}
export KEEPDATA=YES

export HOMEhafs=${HOMEhafs:-${OPSROOT:?}/hafs.${hafs_ver:?}}
export USHhafs=$HOMEhafs/ush
export EXEChafs=$HOMEhafs/exec
export PARMhafs=$HOMEhafs/parm
export FIXhafs=$HOMEhafs/fix

export WORKhafs=${WORKhafs:-${DATAROOT:?}/${RUN:?}${storm_num:?}_${cyc:?}_${envir:?}_${hafs_ver:?}}

if [[ "${ANALYSIS_MODEL}" = "GSI" ]]; then
  if [[ "${RUN_ENVIR^^}" != "NCO" ]]; then
    # Detect platform and load modules if not run by NCO
    source ${USHhafs}/hafs_pre_job.sh.inc
    export machine=${WHERE_AM_I:-wcoss2}
    if [[ ${machine}  = "orion" ]] || [[ ${machine}  = "hercules" ]] || [[ ${machine}  = "hera" ]] || [[ ${machine}  = "gaeac6" ]] || [[ ${machine}  = "ursa" ]]; then
      module purge
      module use $HOMEhafs/sorc/hafs_gsi.fd/modulefiles
      module load gsi_${machine}.intel
    fi
    module list
  else
    # Run by NCO on WCOSS2
    export machine=${WHERE_AM_I:-wcoss2}
    # Prepend $USHhafs to python package search path
    export PYTHONPATH=$USHhafs${PYTHONPATH:+:$PYTHONPATH}
    # Initialize PDY
  # setpdy.sh # only needed for the launch job
    # Get PDY
    source ${WORKhafs}/PDY
  fi
  else
  source ${USHhafs}/hafs_pre_job.sh.inc
  export machine=${WHERE_AM_I:-wcoss2}
  if [[ ${machine}  = "wcoss2" ]]; then
    module reset
    module load PrgEnv-intel/${PrgEnv_intel_ver}
    module load craype/${craype_ver}
    module load intel/${intel_ver}
    module load cray-mpich/${cray_mpich_ver}
    module load cray-pals/${cray_pals_ver}
    module load hdf5-A/${hdf5_ver}
    module load netcdf-A/${netcdf_ver}
    module load ve/hafs/${ve_hafs_ver}
    module load crtm/${crtm_ver}
    module load ncio-A/${ncio_ver}
    module load ncdiag-A/${ncdiag_ver}
    module load cfp/${cfp_ver}
    module load prod_util/${prod_util_ver}
  fi
  if [[ ${machine}  = "jet" ]] || [[ ${machine}  = "orion" ]] || [[ ${machine}  = "hercules" ]] || [[ ${machine}  = "hera" ]] || [[ ${machine}  = "ursa" ]]; then
    module purge
  fi
  if [[ ${machine}  = "gaeac6" ]]; then
    module reset
  fi
  ulimit -s unlimited
  ulimit -a
  module use $HOMEhafs/sorc/hafs_jedi.fd/modulefiles
  module load HDAS/${machine}.intel
  if [[ ${machine}  = "ursa" ]] || [[ ${machine}  = "jet" ]]; then
    module load intel-oneapi-mkl/2024.2.1
  fi
  export PYTHONPATH="${PYTHONPATH}:$HOMEhafs/sorc/hafs_jedi.fd/sorc/jcb/src/:$HOMEhafs/sorc/hafs_jedi.fd/sorc/hafs_jedi.fd/build/lib/python3.*"
  export SALLOC_ACCOUNT=$SLURM_JOB_ACCOUNT
  export SBATCH_ACCOUNT=$SLURM_JOB_ACCOUNT
  export IODA_PRINT_RUNSTATS=1
  export OMP_NUM_THREADS=1
  export OMP_PROC_BIND=true
  export I_MPI_COLL_INTRANODE=pt2pt
fi

source ${USHhafs}/hafs_runcmd.sh.inc

env

export COMhafs=${COMhafs:-$(compath.py ${envir}/${NET}/${hafs_ver})/${RUN}.${PDY}/${cyc}}
export CONFhafs=$COMhafs/$stormlabel.conf
export HOLDVARS=${HOLDVARS:-$COMhafs/$stormlabel.holdvars.txt}

source ${HOLDVARS}

export ENSDA=${ENSDA:-NO}
export HX_ENS=${HX_ENS:-NO}

if [[ ${HX_ENS:-NO} = YES ]]; then
  export ENSID=${ENSID:-001}
  export MEMSTR="mem${ENSID}"
else
  export ENSID="mean"
  export MEMSTR="ensmean"
fi

export DATA=${WORKhafs}/enkf_hx/${MEMSTR}${jobidstr}

if [[ "${SCRUBDATA:-YES}" = YES ]]; then
  rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA

# Execute ex-script
if [[ "${ANALYSIS_MODEL}" = "JEDI" ]] || [[ "${ANALYSIS_MODEL}" = "jedi" ]]; then
  ${NLN} ${HOMEhafs}/ush/wxflow .
  ${HOMEhafs}/scripts/exhafs_atm_enkf_hx.sh
#JEDI ENKF DOES NOT NEED PRE CALCULATION OF HOFX ANYMORE, KEPT FOR DIAGNOSTIC POTENTIAL
else
  ${HOMEhafs}/scripts/exhafs_enkf_hx.sh
fi
export err=$?; err_chk

# Cleanup DATA dir
cd ${WORKhafs}
if [[ "${KEEPDATA:-YES}" != "YES" ]]; then
  rm -rf $DATA
fi

date
