#!/bin/sh

date
export PS4='+ $SECONDS + '
set -xue

export cycle=${cycle:-t${cyc:?}z}
export storm_num=${storm_num:-1}
export stormlabel=${stormlabel:-storm$storm_num}
export hafs_ver=${hafs_ver:?}
export NET=${NET:?}
export RUN=${RUN:?}
export RUN_ENVIR=${RUN_ENVIR:?}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}
export EMAIL_SDM=${EMAIL_SDM:-NO}
export SCRUBDATA=${SCRUBDATA:-YES}
# HAFS workflow jobs use shared working dir, and the CLEANUP or SCRUB job will clean up WORKhafs
#export KEEPDATA=${KEEPDATA:-YES}
export KEEPDATA=YES

export HOMEhafs=${HOMEhafs:-${OPSROOT:?}/hafs.${hafs_ver:?}}
export USHhafs=$HOMEhafs/ush
export EXEChafs=$HOMEhafs/exec
export PARMhafs=$HOMEhafs/parm
export FIXhafs=$HOMEhafs/fix

export WORKhafs=${WORKhafs:-${DATAROOT:?}/${RUN:?}${storm_num:?}_${cyc:?}_${envir:?}_${hafs_ver:?}}

if [ "${RUN_ENVIR^^}" != "NCO" ]; then
  # Detect platform and load modules if not run by NCO
  source ${USHhafs}/hafs_pre_job.sh.inc
  export machine=${WHERE_AM_I:-wcoss2}
  if [ "${GRAPH}" = "EMC" ]; then
    if [ ${machine} = hera ]; then 
       module purge
    fi
    module use ${HOMEhafs}/sorc/hafs_graphics.fd/emc_graphics/modulefiles
    module load graphics.run.${machine}
  elif [ "${GRAPH}" = "HRD" ]; then
    source ${HOMEhafs}/sorc/hafs_graphics.fd/hrd_gplot/modulefiles/modulefile.gplot.${machine}
  else
    echo "FATAL ERROR: Wrong GRAPH option ${GRAPH}, should be either EMC or HRD."
    exit 1
  fi
  module list
else
  # Run by NCO on WCOSS2
  export machine=${WHERE_AM_I:-wcoss2}
  # Prepend $USHhafs to python package search path
  export PYTHONPATH=$USHhafs${PYTHONPATH:+:$PYTHONPATH}
  # Initialize PDY
# setpdy.sh # only needed for the launch job
  # Get PDY
  source ${WORKhafs}/PDY
fi

source ${USHhafs}/hafs_runcmd.sh.inc

env

export COMhafs=${COMhafs:-$(compath.py ${envir}/${NET}/${hafs_ver})/${RUN}.${PDY}/${cyc}}
export CONFhafs=$COMhafs/$stormlabel.conf
export HOLDVARS=${HOLDVARS:-$COMhafs/$stormlabel.holdvars.txt}

source ${HOLDVARS}

export HOMEgraph=${HOMEgraph:-${HOMEhafs}/sorc/hafs_graphics.fd/emc_graphics}
export USHgraph=${USHgraph:-${HOMEgraph}/ush}
export WORKgraph=${WORKgraph:-${WORKhafs}/emc_graphics}
export COMgraph=${COMgraph:-${COMhafs}/emc_graphics}

export ADECKgraph=${ADECKhafs:?}
export BDECKgraph=${BDECKhafs:?}
export SYNDAThafs=${SYNDAThafs:?}
export cartopyDataDir=${cartopyDataDir:?}

export GPLOThafs=${GPLOThafs:-${HOMEhafs}/sorc/hafs_graphics.fd/hrd_gplot}
export GPLOT_DIR=${GPLOThafs}

if [ "${GRAPH}" = "EMC" ]; then
  export DATA=${WORKgraph}
  exscript=exhafs_emcgraphics.sh
elif [ "${GRAPH}" = "HRD" ]; then
  export DATA=${WORKhafs}/hrdgraphics
  exscript=exhafs_hrdgraphics.sh
else
  echo "FATAL ERROR: Wrong GRAPH option ${GRAPH}, should be either EMC or HRD."
  exit 1
fi

if [ "${SCRUBDATA:-YES}" = "YES" ]; then
  rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA

# Execute ex-script
${HOMEhafs}/scripts/${exscript}
export err=$?; err_chk

# Cleanup DATA dir
cd ${WORKhafs}
if [ "${KEEPDATA:-YES}" != "YES" ]; then
  rm -rf $DATA
fi

date
