#!/bin/sh

date
export PS4='+ $SECONDS + '
set -xue

export HOMEhafs=${HOMEhafs:?}
export USHhafs=${USHhafs:-${HOMEhafs}/ush}
export EXEChafs=${EXEChafs:-${HOMEhafs}/exec}
export PARMhafs=${PARMhafs:-${HOMEhafs}/parm}
export FIXhafs=${FIXhafs:-${HOMEhafs}/fix}

source ${USHhafs}/hafs_pre_job.sh.inc
source ${HOLDVARS:-storm1.holdvars.txt}

export machine=${WHERE_AM_I:-wcoss_cray}
export envir=${envir:-prod} # prod, para, test
export RUN_ENVIR=${RUN_ENVIR:-dev} # nco or dev
if [ "${RUN_ENVIR^^}" != NCO ]; then
  module use ${HOMEhafs}/modulefiles
  module load modulefile.hafs.${machine}
  module list
fi

source ${USHhafs}/hafs_runcmd.sh.inc

# Run setpdy and initialize PDY variables
#setpdy.sh
#. ./PDY
export PDY=${PDY:-$(echo ${YMDH} | cut -c 1-8 )}

export WORKhafs=${WORKhafs:?}
export COMIN=${COMIN:?}
export COMOUT=${COMOUT:?}
export COMhafs=${COMhafs:-${COMOUT}}

export CDATE=${CDATE:-${YMDH}}
export cyc=${cyc:?}
export STORM=${STORM:-FAKE}
export STORMID=${STORMID:-00L}
export ENSDA=${ENSDA:-NO}
export FGAT_MODEL=${FGAT_MODEL:-gfs}
export FGAT_HR=${FGAT_HR:-00}

NDATE=${NDATE:-ndate}
CDATEprior=`${NDATE} -6 $CDATE`
PDYprior=`echo ${CDATEprior} | cut -c1-8`
cycprior=`echo ${CDATEprior} | cut -c9-10`
yrprior=`echo ${CDATEprior} | cut -c1-4`
mnprior=`echo ${CDATEprior} | cut -c5-6`
dyprior=`echo ${CDATEprior} | cut -c7-8`
hhprior=`echo ${CDATEprior} | cut -c9-10`
export COMhafsprior=${COMhafsprior:-${COMhafs}/../../${CDATEprior}/${STORMID}}

# Deterministic or ensemble
if [ "${ENSDA}" = YES ]; then
  export ENSID=${ENSID:-001}
  export RESTARTinp=${COMhafsprior}/RESTART_ens/mem${ENSID}
  export RESTARTenv=${WORKhafs}/intercom/RESTART_init_ens/mem${ENSID}
  export RESTARTout=${WORKhafs}/intercom/RESTART_vi_ens/mem${ENSID}
  export DATA=${WORKhafs}/atm_vi_ens/mem${ENSID}
elif [ ${FGAT_MODEL} = gdas ]; then
  export RESTARTinp=${COMhafsprior}/RESTART
  export RESTARTenv=${COMhafs}/RESTART_init_fgat${FGAT_HR}
  export RESTARTout=${COMhafs}/RESTART_vi_fgat${FGAT_HR}
  export DATA=${WORKhafs}/atm_vi_fgat${FGAT_HR}
  export CDATE=$(${NDATE} $(awk "BEGIN {print ${FGAT_HR}-6}") $CDATE)
else
  export RESTARTinp=${COMhafsprior}/RESTART
  export RESTARTenv=${COMhafs}/RESTART_init
  export RESTARTout=${COMhafs}/RESTART_vi
  export DATA=${WORKhafs}/atm_vi
fi

export SCRUBDATA=${SCRUBDATA:-YES}
if [ "${SCRUBDATA}" = YES ]; then
  rm -rf $DATA
fi

mkdir -p $DATA
cd $DATA

# Execute ex-script
${HOMEhafs}/scripts/exhafs_atm_vi.sh
export err=$?
exit $err

export KEEPDATA=${KEEPDATA:-YES}
if [ "${KEEPDATA^^}" != YES ]; then
  rm -rf $DATA
fi

date
