#################################################################################
#
# make to run the script that calls the make to make everything
# 

all:	runmake

runmake:
	./run_makefile.sh

clean:
	/bin/rm -f *.o *.mod *.F.f dimensions.h \
	../../exec/hwrf_rtofs_*_forecast 
