#!/bin/sh
set -x -e
module reset
module load intel/19.1.3.304
module load hdf5/1.10.6
module load netcdf/4.7.4
module load udunits/2.2.28
module load gsl/2.7
module load nco/4.9.7
module list
#NCAP2=$(which ncap2)
NCAP2=${NCO_ROOT}/bin/ncap2
exec ${NCAP2} "$@"
#exec ncap2 "$@"
