#!/bin/bash --login
#
# Specify the account
#$ -A hfipcira
#
# Specify the PE and number of cores
#$ -pe hfipdebug 1
#
# Specify the wallclock time in HH:MM:SS
#$ -l h_rt=00:30:00
#
# Automatically change the directory to where the job was launched
#$ -cwd
#
# Join the stdout and stderr output streams
#$ -j y

# Set a variable with the number of cores (slots) your
# job will use.  This makes it easier so that when you
# make changes to the number of cores used, it only
# gets changed in one place.
#set np=$NSLOTS
#
# Run the job
./create_diagfiles.sh
