#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <glob.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>

int main(int argc,char **argv) {
  printf("!! Do not edit this file.  It is automatically generated.\n");
  printf("!! Edit %s.in instead.\n",__FILE__);
  printf("module sia_const\n");
  printf("use iso_c_binding, only: c_int64_t\n");
  printf("implicit none\n");
  printf("\n");
  printf("! glob.h constants\n");
#ifdef GLOB_ERR
  printf("integer(kind=c_int64_t), parameter :: GLOB_ERR             = %lld\n",
         (long long)      GLOB_ERR);
  printf("logical                , parameter :: have_GLOB_ERR        = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::             GLOB_ERR = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_ERR        = .false.\n");
#endif
#ifdef GLOB_MARK
  printf("integer(kind=c_int64_t), parameter :: GLOB_MARK            = %lld\n",
         (long long)     GLOB_MARK);
  printf("logical                , parameter :: have_GLOB_MARK       = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::            GLOB_MARK = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_MARK       = .false.\n");
#endif
#ifdef GLOB_NOSORT
  printf("integer(kind=c_int64_t), parameter :: GLOB_NOSORT          = %lld\n",
         (long long)   GLOB_NOSORT);
  printf("logical                , parameter :: have_GLOB_NOSORT     = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::          GLOB_NOSORT = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_NOSORT     = .false.\n");
#endif
#ifdef GLOB_DOOFS
  printf("integer(kind=c_int64_t), parameter :: GLOB_DOOFS           = %lld\n",
         (long long)    GLOB_DOOFS);
  printf("logical                , parameter :: have_GLOB_DOOFS      = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::           GLOB_DOOFS = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_DOOFS      = .false.\n");
#endif
#ifdef GLOB_NOCHECK
  printf("integer(kind=c_int64_t), parameter :: GLOB_NOCHECK         = %lld\n",
         (long long)  GLOB_NOCHECK);
  printf("logical                , parameter :: have_GLOB_NOCHECK    = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::         GLOB_NOCHECK = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_NOCHECK    = .false.\n");
#endif
#ifdef GLOB_APPEND
  printf("integer(kind=c_int64_t), parameter :: GLOB_APPEND          = %lld\n",
         (long long)   GLOB_APPEND);
  printf("logical                , parameter :: have_GLOB_APPEND     = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::          GLOB_APPEND = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_APPEND     = .false.\n");
#endif
#ifdef GLOB_NOESCAPE
  printf("integer(kind=c_int64_t), parameter :: GLOB_NOESCAPE        = %lld\n",
         (long long) GLOB_NOESCAPE);
  printf("logical                , parameter :: have_GLOB_NOESCAPE   = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::        GLOB_NOESCAPE = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_NOESCAPE   = .false.\n");
#endif
#ifdef GLOB_PERIOD
  printf("integer(kind=c_int64_t), parameter :: GLOB_PERIOD          = %lld\n",
         (long long)   GLOB_PERIOD);
  printf("logical                , parameter :: have_GLOB_PERIOD     = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::          GLOB_PERIOD = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_PERIOD     = .false.\n");
#endif
#ifdef GLOB_ALTDIRFUNC
  printf("integer(kind=c_int64_t), parameter :: GLOB_ALTDIRFUNC      = %lld\n",
         (long long)GLOB_ALTDIRFUNC);
  printf("logical                , parameter :: have_GLOB_ALTDIRFUNC = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::      GLOB_ALTDIRFUNC = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_ALTDIRFUNC = .false.\n");
#endif
#ifdef GLOB_BRACE
  printf("integer(kind=c_int64_t), parameter :: GLOB_BRACE           = %lld\n",
         (long long)    GLOB_BRACE);
  printf("logical                , parameter :: have_GLOB_BRACE      = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::           GLOB_BRACE = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_BRACE      = .false.\n");
#endif
#ifdef GLOB_NOMAGIC
  printf("integer(kind=c_int64_t), parameter :: GLOB_NOMAGIC         = %lld\n",
         (long long)  GLOB_NOMAGIC);
  printf("logical                , parameter :: have_GLOB_NOMAGIC    = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::         GLOB_NOMAGIC = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_NOMAGIC    = .false.\n");
#endif
#ifdef GLOB_TILDE
  printf("integer(kind=c_int64_t), parameter :: GLOB_TILDE           = %lld\n",
         (long long)    GLOB_TILDE);
  printf("logical                , parameter :: have_GLOB_TILDE      = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::           GLOB_TILDE = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_TILDE      = .false.\n");
#endif
#ifdef GLOB_TILDE_CHECK
  printf("integer(kind=c_int64_t), parameter :: GLOB_TILDE_CHECK     = %lld\n",
         (long long)GLOB_TILDE_CHECK);
  printf("logical                , parameter :: have_GLOB_TILDE_CHECK = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::     GLOB_TILDE_CHECK = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_TILDE_CHECK = .false.\n");
#endif
#ifdef GLOB_ONLYDIR
  printf("integer(kind=c_int64_t), parameter :: GLOB_ONLYDIR         = %lld\n",
         (long long)  GLOB_ONLYDIR);
  printf("logical                , parameter :: have_GLOB_ONLYDIR    = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::         GLOB_ONLYDIR = 0 ! missing\n");
  printf("logical                , parameter :: have_GLOB_ONLYDIR    = .false.\n");
#endif
printf("\n");
  printf("! stat constants\n");
#ifdef S_IFMT
  printf("integer(kind=c_int64_t), parameter :: S_IFMT               = %lld\n",
         (long long)        S_IFMT);
  printf("logical                , parameter :: have_S_IFMT          = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::               S_IFMT = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IFMT          = .false.\n");
#endif
#ifdef S_IFSOCK
  printf("integer(kind=c_int64_t), parameter :: S_IFSOCK             = %lld\n",
         (long long)      S_IFSOCK);
  printf("logical                , parameter :: have_S_IFSOCK        = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::             S_IFSOCK = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IFSOCK        = .false.\n");
#endif
#ifdef S_IFLNK
  printf("integer(kind=c_int64_t), parameter :: S_IFLNK              = %lld\n",
         (long long)       S_IFLNK);
  printf("logical                , parameter :: have_S_IFLNK         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IFLNK = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IFLNK         = .false.\n");
#endif
#ifdef S_IFREG
  printf("integer(kind=c_int64_t), parameter :: S_IFREG              = %lld\n",
         (long long)       S_IFREG);
  printf("logical                , parameter :: have_S_IFREG         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IFREG = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IFREG         = .false.\n");
#endif
#ifdef S_IFBLK
  printf("integer(kind=c_int64_t), parameter :: S_IFBLK              = %lld\n",
         (long long)       S_IFBLK);
  printf("logical                , parameter :: have_S_IFBLK         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IFBLK = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IFBLK         = .false.\n");
#endif
#ifdef S_IFDIR
  printf("integer(kind=c_int64_t), parameter :: S_IFDIR              = %lld\n",
         (long long)       S_IFDIR);
  printf("logical                , parameter :: have_S_IFDIR         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IFDIR = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IFDIR         = .false.\n");
#endif
#ifdef S_IFCHR
  printf("integer(kind=c_int64_t), parameter :: S_IFCHR              = %lld\n",
         (long long)       S_IFCHR);
  printf("logical                , parameter :: have_S_IFCHR         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IFCHR = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IFCHR         = .false.\n");
#endif
#ifdef S_IFIFO
  printf("integer(kind=c_int64_t), parameter :: S_IFIFO              = %lld\n",
         (long long)       S_IFIFO);
  printf("logical                , parameter :: have_S_IFIFO         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IFIFO = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IFIFO         = .false.\n");
#endif
#ifdef S_ISUID
  printf("integer(kind=c_int64_t), parameter :: S_ISUID              = %lld\n",
         (long long)       S_ISUID);
  printf("logical                , parameter :: have_S_ISUID         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_ISUID = 0 ! missing\n");
  printf("logical                , parameter :: have_S_ISUID         = .false.\n");
#endif
#ifdef S_ISGID
  printf("integer(kind=c_int64_t), parameter :: S_ISGID              = %lld\n",
         (long long)       S_ISGID);
  printf("logical                , parameter :: have_S_ISGID         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_ISGID = 0 ! missing\n");
  printf("logical                , parameter :: have_S_ISGID         = .false.\n");
#endif
#ifdef S_ISVTX
  printf("integer(kind=c_int64_t), parameter :: S_ISVTX              = %lld\n",
         (long long)       S_ISVTX);
  printf("logical                , parameter :: have_S_ISVTX         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_ISVTX = 0 ! missing\n");
  printf("logical                , parameter :: have_S_ISVTX         = .false.\n");
#endif
#ifdef S_IRWXU
  printf("integer(kind=c_int64_t), parameter :: S_IRWXU              = %lld\n",
         (long long)       S_IRWXU);
  printf("logical                , parameter :: have_S_IRWXU         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IRWXU = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IRWXU         = .false.\n");
#endif
#ifdef S_IRUSR
  printf("integer(kind=c_int64_t), parameter :: S_IRUSR              = %lld\n",
         (long long)       S_IRUSR);
  printf("logical                , parameter :: have_S_IRUSR         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IRUSR = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IRUSR         = .false.\n");
#endif
#ifdef S_IWUSR
  printf("integer(kind=c_int64_t), parameter :: S_IWUSR              = %lld\n",
         (long long)       S_IWUSR);
  printf("logical                , parameter :: have_S_IWUSR         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IWUSR = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IWUSR         = .false.\n");
#endif
#ifdef S_IXUSR
  printf("integer(kind=c_int64_t), parameter :: S_IXUSR              = %lld\n",
         (long long)       S_IXUSR);
  printf("logical                , parameter :: have_S_IXUSR         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IXUSR = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IXUSR         = .false.\n");
#endif
#ifdef S_IRWXG
  printf("integer(kind=c_int64_t), parameter :: S_IRWXG              = %lld\n",
         (long long)       S_IRWXG);
  printf("logical                , parameter :: have_S_IRWXG         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IRWXG = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IRWXG         = .false.\n");
#endif
#ifdef S_IRGRP
  printf("integer(kind=c_int64_t), parameter :: S_IRGRP              = %lld\n",
         (long long)       S_IRGRP);
  printf("logical                , parameter :: have_S_IRGRP         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IRGRP = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IRGRP         = .false.\n");
#endif
#ifdef S_IWGRP
  printf("integer(kind=c_int64_t), parameter :: S_IWGRP              = %lld\n",
         (long long)       S_IWGRP);
  printf("logical                , parameter :: have_S_IWGRP         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IWGRP = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IWGRP         = .false.\n");
#endif
#ifdef S_IXGRP
  printf("integer(kind=c_int64_t), parameter :: S_IXGRP              = %lld\n",
         (long long)       S_IXGRP);
  printf("logical                , parameter :: have_S_IXGRP         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IXGRP = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IXGRP         = .false.\n");
#endif
#ifdef S_IRWXO
  printf("integer(kind=c_int64_t), parameter :: S_IRWXO              = %lld\n",
         (long long)       S_IRWXO);
  printf("logical                , parameter :: have_S_IRWXO         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IRWXO = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IRWXO         = .false.\n");
#endif
#ifdef S_IROTH
  printf("integer(kind=c_int64_t), parameter :: S_IROTH              = %lld\n",
         (long long)       S_IROTH);
  printf("logical                , parameter :: have_S_IROTH         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IROTH = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IROTH         = .false.\n");
#endif
#ifdef S_IWOTH
  printf("integer(kind=c_int64_t), parameter :: S_IWOTH              = %lld\n",
         (long long)       S_IWOTH);
  printf("logical                , parameter :: have_S_IWOTH         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IWOTH = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IWOTH         = .false.\n");
#endif
#ifdef S_IXOTH
  printf("integer(kind=c_int64_t), parameter :: S_IXOTH              = %lld\n",
         (long long)       S_IXOTH);
  printf("logical                , parameter :: have_S_IXOTH         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              S_IXOTH = 0 ! missing\n");
  printf("logical                , parameter :: have_S_IXOTH         = .false.\n");
#endif
printf("\n");
  printf("! Signal numbers\n");
#ifdef SIGHUP
  printf("integer(kind=c_int64_t), parameter :: SIGHUP               = %lld\n",
         (long long)        SIGHUP);
  printf("logical                , parameter :: have_SIGHUP          = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::               SIGHUP = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGHUP          = .false.\n");
#endif
#ifdef SIGINT
  printf("integer(kind=c_int64_t), parameter :: SIGINT               = %lld\n",
         (long long)        SIGINT);
  printf("logical                , parameter :: have_SIGINT          = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::               SIGINT = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGINT          = .false.\n");
#endif
#ifdef SIGQUIT
  printf("integer(kind=c_int64_t), parameter :: SIGQUIT              = %lld\n",
         (long long)       SIGQUIT);
  printf("logical                , parameter :: have_SIGQUIT         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGQUIT = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGQUIT         = .false.\n");
#endif
#ifdef SIGILL
  printf("integer(kind=c_int64_t), parameter :: SIGILL               = %lld\n",
         (long long)        SIGILL);
  printf("logical                , parameter :: have_SIGILL          = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::               SIGILL = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGILL          = .false.\n");
#endif
#ifdef SIGABRT
  printf("integer(kind=c_int64_t), parameter :: SIGABRT              = %lld\n",
         (long long)       SIGABRT);
  printf("logical                , parameter :: have_SIGABRT         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGABRT = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGABRT         = .false.\n");
#endif
#ifdef SIGFPE
  printf("integer(kind=c_int64_t), parameter :: SIGFPE               = %lld\n",
         (long long)        SIGFPE);
  printf("logical                , parameter :: have_SIGFPE          = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::               SIGFPE = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGFPE          = .false.\n");
#endif
#ifdef SIGKILL
  printf("integer(kind=c_int64_t), parameter :: SIGKILL              = %lld\n",
         (long long)       SIGKILL);
  printf("logical                , parameter :: have_SIGKILL         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGKILL = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGKILL         = .false.\n");
#endif
#ifdef SIGSEGV
  printf("integer(kind=c_int64_t), parameter :: SIGSEGV              = %lld\n",
         (long long)       SIGSEGV);
  printf("logical                , parameter :: have_SIGSEGV         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGSEGV = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGSEGV         = .false.\n");
#endif
#ifdef SIGPIPE
  printf("integer(kind=c_int64_t), parameter :: SIGPIPE              = %lld\n",
         (long long)       SIGPIPE);
  printf("logical                , parameter :: have_SIGPIPE         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGPIPE = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGPIPE         = .false.\n");
#endif
#ifdef SIGALRM
  printf("integer(kind=c_int64_t), parameter :: SIGALRM              = %lld\n",
         (long long)       SIGALRM);
  printf("logical                , parameter :: have_SIGALRM         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGALRM = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGALRM         = .false.\n");
#endif
#ifdef SIGTERM
  printf("integer(kind=c_int64_t), parameter :: SIGTERM              = %lld\n",
         (long long)       SIGTERM);
  printf("logical                , parameter :: have_SIGTERM         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGTERM = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGTERM         = .false.\n");
#endif
#ifdef SIGUSR1
  printf("integer(kind=c_int64_t), parameter :: SIGUSR1              = %lld\n",
         (long long)       SIGUSR1);
  printf("logical                , parameter :: have_SIGUSR1         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGUSR1 = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGUSR1         = .false.\n");
#endif
#ifdef SIGUSR2
  printf("integer(kind=c_int64_t), parameter :: SIGUSR2              = %lld\n",
         (long long)       SIGUSR2);
  printf("logical                , parameter :: have_SIGUSR2         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGUSR2 = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGUSR2         = .false.\n");
#endif
#ifdef SIGCHLD
  printf("integer(kind=c_int64_t), parameter :: SIGCHLD              = %lld\n",
         (long long)       SIGCHLD);
  printf("logical                , parameter :: have_SIGCHLD         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGCHLD = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGCHLD         = .false.\n");
#endif
#ifdef SIGCONT
  printf("integer(kind=c_int64_t), parameter :: SIGCONT              = %lld\n",
         (long long)       SIGCONT);
  printf("logical                , parameter :: have_SIGCONT         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGCONT = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGCONT         = .false.\n");
#endif
#ifdef SIGSTOP
  printf("integer(kind=c_int64_t), parameter :: SIGSTOP              = %lld\n",
         (long long)       SIGSTOP);
  printf("logical                , parameter :: have_SIGSTOP         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGSTOP = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGSTOP         = .false.\n");
#endif
#ifdef SIGTSTP
  printf("integer(kind=c_int64_t), parameter :: SIGTSTP              = %lld\n",
         (long long)       SIGTSTP);
  printf("logical                , parameter :: have_SIGTSTP         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGTSTP = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGTSTP         = .false.\n");
#endif
#ifdef SIGTTIN
  printf("integer(kind=c_int64_t), parameter :: SIGTTIN              = %lld\n",
         (long long)       SIGTTIN);
  printf("logical                , parameter :: have_SIGTTIN         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGTTIN = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGTTIN         = .false.\n");
#endif
#ifdef SIGTTOU
  printf("integer(kind=c_int64_t), parameter :: SIGTTOU              = %lld\n",
         (long long)       SIGTTOU);
  printf("logical                , parameter :: have_SIGTTOU         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGTTOU = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGTTOU         = .false.\n");
#endif
#ifdef SIGBUS
  printf("integer(kind=c_int64_t), parameter :: SIGBUS               = %lld\n",
         (long long)        SIGBUS);
  printf("logical                , parameter :: have_SIGBUS          = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::               SIGBUS = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGBUS          = .false.\n");
#endif
#ifdef SIGPOLL
  printf("integer(kind=c_int64_t), parameter :: SIGPOLL              = %lld\n",
         (long long)       SIGPOLL);
  printf("logical                , parameter :: have_SIGPOLL         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGPOLL = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGPOLL         = .false.\n");
#endif
#ifdef SIGIO
  printf("integer(kind=c_int64_t), parameter :: SIGIO                = %lld\n",
         (long long)         SIGIO);
  printf("logical                , parameter :: have_SIGIO           = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::                SIGIO = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGIO           = .false.\n");
#endif
#ifdef SIGPROF
  printf("integer(kind=c_int64_t), parameter :: SIGPROF              = %lld\n",
         (long long)       SIGPROF);
  printf("logical                , parameter :: have_SIGPROF         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGPROF = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGPROF         = .false.\n");
#endif
#ifdef SIGSYS
  printf("integer(kind=c_int64_t), parameter :: SIGSYS               = %lld\n",
         (long long)        SIGSYS);
  printf("logical                , parameter :: have_SIGSYS          = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::               SIGSYS = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGSYS          = .false.\n");
#endif
#ifdef SIGTRAP
  printf("integer(kind=c_int64_t), parameter :: SIGTRAP              = %lld\n",
         (long long)       SIGTRAP);
  printf("logical                , parameter :: have_SIGTRAP         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGTRAP = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGTRAP         = .false.\n");
#endif
#ifdef SIGURG
  printf("integer(kind=c_int64_t), parameter :: SIGURG               = %lld\n",
         (long long)        SIGURG);
  printf("logical                , parameter :: have_SIGURG          = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::               SIGURG = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGURG          = .false.\n");
#endif
#ifdef SIGVTALRM
  printf("integer(kind=c_int64_t), parameter :: SIGVTALRM            = %lld\n",
         (long long)     SIGVTALRM);
  printf("logical                , parameter :: have_SIGVTALRM       = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::            SIGVTALRM = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGVTALRM       = .false.\n");
#endif
#ifdef SIGXCPU
  printf("integer(kind=c_int64_t), parameter :: SIGXCPU              = %lld\n",
         (long long)       SIGXCPU);
  printf("logical                , parameter :: have_SIGXCPU         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGXCPU = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGXCPU         = .false.\n");
#endif
#ifdef SIGXFSZ
  printf("integer(kind=c_int64_t), parameter :: SIGXFSZ              = %lld\n",
         (long long)       SIGXFSZ);
  printf("logical                , parameter :: have_SIGXFSZ         = .true.\n");
#else
  printf("integer(kind=c_int64_t), parameter ::              SIGXFSZ = 0 ! missing\n");
  printf("logical                , parameter :: have_SIGXFSZ         = .false.\n");
#endif
printf("end module sia_const\n");
  return 0;
}
